### PR TITLE
fix(route): fix the error of route hk01/channel when channel does not have publishName

### LINKED ISSUE #12141: 希望可以添加香港01即时路由
### 这是一个什么样的功能？

image

### 这个功能可以解决什么问题？

此路由可以包含网站一切即时发布的新闻和文章

### 额外描述

_No response_

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

### PR DESCRIPTION
**Pull request by 5upernova-heng**
## 该 PR 相关 Issue / Involved issue

Close #12141 

## 完整路由地址 / Example for the proposed route(s)

```routes
/hk01/channel/1
/hk01/latest
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [x] 新的路由 New Route
  - [x] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [x] 文档说明 Documentation
  - [x] 中文文档 CN
  - [ ] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

## 说明 / Note
In #12141 "即时" can be fetched by api `https://web-data.api.hk01.com/v2/feed/category/:id`, which is already implemented by route `/hk01/channel/:id`.

However, categories(or channels) like "即时" does not have `category` object in its json data. This will cause an error when using it's property to be the title of the rss feed. For example `/hk01/channel/0`. This commit is to fix this problem.

What's more, the only way I've found to get rss subscription like "即时", is to look up what the api the page called, which might be hard for those users who are not familiar with web to find the `id` of the page they want. It will be better if there's a proper solution to this problem.

### CODE REVIEW

**Review by TonyRL — CHANGES_REQUESTED** [review]
This does not close #12141 at all. #12141 uses a different API than `lib/v2/hk01/channel.js`

**Comment by 5upernova-heng** [comment]
> This does not close #12141 at all. #12141 uses a different API than `lib/v2/hk01/channel.js`

You are right. #12141 uses a different API. Should I open other PR to do this, or just in this one?

**Comment by TonyRL** [comment]
Simply push everything to this PR is enough.

**Comment by 5upernova-heng** [comment]
It seems that `whatsmyua.info` website is down right now(used in Jest test). How can I rerun the test later?

**Pull request merged**
