### PR TITLE
feat(route): add github issues/pull comments

### LINKED ISSUE #8116: RSS Feed for Github comments from a particular issue
### What feature is it?
Currently there's a feed for new issues on a particular repository but there isn't a feed for comments on an individual issue. 
### What problem does this feature solve?
I would like to be updated whenever there's a new comment on an issue i am following
### Additional description
As an example I would like to be able to follow any changes to this issue user-DIYgod, repository-RSSHub, issue-8116

### PR DESCRIPTION
**Pull request by TonyRL**
## 该 PR 相关 Issue / Involved issue

Close #8116

## 完整路由地址 / Example for the proposed route(s)

```routes
/github/comments/DIYgod/RSSHub/issues/8116
/github/comments/torvalds/linux/pull/765
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [x] New Route
- [x] Documentation
  - [x] CN
  - [x] EN
- [x] 全文获取 fulltext
  - [x] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] 日期和时间 date and time
  - [x] 可以解析 Parsed
  - [x] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

### CODE REVIEW

**Review by NeverBehave — COMMENTED** [review]
方便直接迁移到新版本里面吗？

**Comment by TonyRL** [comment]
- https://github.com/DIYgod/RSSHub/pull/8128/commits/54d15abedfb73022d557014211194aebd69ba309 migrate to v2 script standard

**Comment by oliroe** [comment]
Hi
Is there anything I can do to help get this over the line? Happy to do any testing etc.
Thanks

**Comment by TonyRL** [comment]
Be patient and wait until it is approved. (Sigh. Look at the number of pending PRs).

**Comment by NeverBehave** [comment]
@oliroe we are currently stuck with the CJS -> ESM brought by the community. It should be back to normal soon as we decided not to follow up at this moment.

**Pull request merged**
