### PR TITLE
fix: Improve route "codeforces" time expression readability

### PR DESCRIPTION
**Pull request by Bubbu0129**
## 完整路由地址 / Example for the proposed route(s)

```routes
/codeforces/contests
```

## 说明 / Note
The time was previously presented bare and coarse. This PR makes it more human-readable.
Plus, `relativeTime` was removed, as it only depends on when the endpoint is requested.

### CODE REVIEW

**Review by TonyRL — COMMENTED** [review]
Please use `dayjs` instead
docs: https://day.js.org/en/

**Comment by Bubbu0129** [comment]
Where? On startTime or durationTime?

**Comment by TonyRL** [comment]
Both, including `sec2str`

**Comment by Bubbu0129** [comment]
Legit?

**Pull request merged**
