### PR TITLE
chore: optimize performance (replace he with entities)

### PR DESCRIPTION
**Pull request by oppilate**
Before:
````shell
➜ ab -k -c 20 -n 250 http://127.0.0.1:1200/initium/feature/zh-hant           
This is ApacheBench, Version 2.3 <$Revision: 1879490 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 100 requests
Completed 200 requests
Finished 250 requests


Server Software:        
Server Hostname:        127.0.0.1
Server Port:            1200

Document Path:          /initium/feature/zh-hant
Document Length:        224091 bytes

Concurrency Level:      20
Time taken for tests:   42.454 seconds
Complete requests:      250
Failed requests:        0
Keep-Alive requests:    250
Total transferred:      56123724 bytes
HTML transferred:       56022750 bytes
Requests per second:    5.89 [#/sec] (mean)
Time per request:       3396.299 [ms] (mean)
Time per request:       169.815 [ms] (mean, across all concurrent requests)
Transfer rate:          1291.01 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.2      0       1
Processing:   131 2773 580.9   2786    6833
Waiting:      131 2772 580.8   2786    6832
Total:        131 2773 580.7   2786    6833

Percentage of the requests served within a certain time (ms)
  50%   2786
  66%   2927
  75%   3030
  80%   3120
  90%   3341
  95%   3400
  98%   3540
  99%   3547
 100%   6833 (longest request)
````

After:
````shell
➜ ab -k -c 20 -n 250 http://127.0.0.1:1200/initium/feature/zh-hant
This is ApacheBench, Version 2.3 <$Revision: 1879490 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 100 requests
Completed 200 requests
Finished 250 requests


Server Software:        
Server Hostname:        127.0.0.1
Server Port:            1200

Document Path:          /initium/feature/zh-hant
Document Length:        224164 bytes

Concurrency Level:      20
Time taken for tests:   14.996 seconds
Complete requests:      250
Failed requests:        0
Keep-Alive requests:    250
Total transferred:      56141974 bytes
HTML transferred:       56041000 bytes
Requests per second:    16.67 [#/sec] (mean)
Time per request:       1199.655 [ms] (mean)
Time per request:       59.983 [ms] (mean, across all concurrent requests)
Transfer rate:          3656.13 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.4      0       3
Processing:    61  704 374.9    650    6173
Waiting:       60  704 374.8    650    6170
Total:         61  704 374.9    650    6173

Percentage of the requests served within a certain time (ms)
  50%    650
  66%    686
  75%    710
  80%    734
  90%    877
  95%   1029
  98%   1101
  99%   1102
 100%   6173 (longest request)
````

### CODE REVIEW

**Comment by DIYgod** [comment]
`entities` should be moved from devDependencies to dependencies https://github.com/DIYgod/RSSHub/blob/18adc60d16e7027ce65a358ee614109112f4fca3/package.json#L44

**Comment by oppilate** [comment]
Wired. So `yarn add entities` won't add it to `dependencies` if it's already in `devDependencies`. Fixed now.

**Comment by oppilate** [comment]
And `parse5` used by cheerio accounts for another 1/3 processing time. Cheerio is capable of handling `htmlparser2`'s parsed dom tree, which is reportedly 5 times faster than `parse5`. But that requires one more line in each cheerio parsing call:
````javascript
// Usage as of htmlparser2 version 3:
const htmlparser2 = require('htmlparser2');
const dom = htmlparser2.parseDOM(document, options);

const $ = cheerio.load(dom);
````

I won't do it right now. Just to take a note here.

**Comment by HenryQW** [comment]
`htmlparser2` is the default now.

https://github.com/cheeriojs/cheerio/pull/985

**Comment by oppilate** [comment]
> htmlparser2 is the default now.

Well, actually it's htmlparser2 for XML and parse5 for HTML: https://github.com/cheeriojs/cheerio/issues/866#issuecomment-749618522. In RSSHub both are used, which matches what I see in the profiling result.

**Pull request merged**
