### PR TITLE
fix(route): 「全国今日生猪价格」 接口地址变更

### LINKED ISSUE #15955: 【全国今日生猪价格】网站换地址  [GET] "https://zhujia.zhuwang.cc//api/chartData?areaId=-1": 502 Bad Gateway
### 路由地址

```routes
/zhuwang/zhujia
```

### 完整路由地址

```fullroutes
/zhuwang/zhujia
```

### 相关文档

https://docs.rsshub.app/routes/shopping#%E5%85%A8%E5%9B%BD%E4%BB%8A%E6%97%A5%E7%94%9F%E7%8C%AA%E4%BB%B7%E6%A0%BC

### 预期是什么？

正常工作

### 实际发生了什么？

网站从https://zhujia.zhuwang.cc/ 变更为  https://xt.yangzhu.vip/

导致报错

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
Error Message:
FetchError: [GET] "https://zhujia.zhuwang.cc//api/chartData?areaId=-1": 502 Bad Gateway

Route: /zhuwang/zhujia

Full Route: /zhuwang/zhujia

Node Version: v22.3.0

Git Hash: 0ba17e15
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by ueiu**
## Involved Issue / 该 PR 相关 Issue

Close #15955

## Example for the Proposed Route(s) / 路由地址示例

```routes
/zhuwang/zhujia
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

### CODE REVIEW

**Comment by KwToPA** [comment]
https://rsshub.app/zhuwang/zhujia

路由恢复了 原因不明

**Comment by KwToPA** [comment]
原来的路由出现故障，报价日期正确，数据出错，一直是7月6日的数据

[2024-7-16 生猪(外三元) 18.57元/公斤. 较昨日价格, 下跌0.2元](https://xt.yangzhu.vip/manage/datamap/ptype/1/areano/-1.html)

官网应该是 https://xt.yangzhu.vip/

**Comment by ueiu** [comment]
> 原来的路由出现故障，报价日期正确，数据出错，一直是7月6日的数据
> 
> [2024-7-16 生猪(外三元) 18.57元/公斤. 较昨日价格, 下跌0.2元](https://xt.yangzhu.vip/manage/datamap/ptype/1/areano/-1.html)
> 
> 官网应该是 https://xt.yangzhu.vip/

@KwToPA 以前是用 https://zhujia.zhuwang.cc/ 访问的，现在新官网是这个也可以吧：https://www.zhuwang.com.cn/

@TonyRL Can you re review and merge? thanks.

**Comment by ueiu** [comment]
/test
```
/zhuwang/zhujia
````

**Comment by TonyRL** [comment]
> @TonyRL Can you re review and merge? thanks.

Please resolve https://github.com/DIYgod/RSSHub/pull/15957#discussion_r1647983633

**Comment by ueiu** [comment]
> > @TonyRL Can you re review and merge? thanks.
> 
> Please resolve [#15957 (comment)](https://github.com/DIYgod/RSSHub/pull/15957#discussion_r1647983633)

However, the content displayed on https://zhujia.zhuwang.cc/ is the same as that on https://www.zhuwang.com.cn/, and I did this for compatibility with the previous homepage. Only the URL for obtaining data has changed to https://zhujia.zhuwang.com.cn/.

**Comment by TonyRL** [comment]
> > > @TonyRL Can you re review and merge? thanks.
> > 
> > 
> > Please resolve [#15957 (comment)](https://github.com/DIYgod/RSSHub/pull/15957#discussion_r1647983633)
> 
> However, the content displayed on https://zhujia.zhuwang.cc/ is the same as that on https://www.zhuwang.com.cn/, and I did this for compatibility with the previous homepage. Only the URL for obtaining data has changed to https://zhujia.zhuwang.com.cn/.
> 
> Refer to this screenshot: image

`baseUrl` only provide the necessary data while `https://www.zhuwang.com.cn/` contains a lot of noise.

<details><summary>Screenshot</summary>

image

</details>

**Comment by KwToPA** [comment]
> > 原来的路由出现故障，报价日期正确，数据出错，一直是7月6日的数据
> > [2024-7-16 生猪(外三元) 18.57元/公斤. 较昨日价格, 下跌0.2元](https://xt.yangzhu.vip/manage/datamap/ptype/1/areano/-1.html)
> > 官网应该是 https://xt.yangzhu.vip/
> 
> @KwToPA 以前是用 https://zhujia.zhuwang.cc/ 访问的，现在新官网是这个也可以吧：https://www.zhuwang.com.cn/
> 
> @TonyRL Can you re review and merge? thanks.

感谢老哥，不过 https://xt.yangzhu.vip/ 这个网站的数据范围显示的是一年，https://www.zhuwang.com.cn/  这个只有一个月

**Comment by ueiu** [comment]
@KwToPA 现在是用 https://zhujia.zhuwang.com.cn/ 做为主页的，而且数据超链接的也是一年范围的数据啊：
image

**Pull request merged**
