### PR TITLE
feat(route): add chinafactcheck

### PR DESCRIPTION
**Pull request by kdanfly**
## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/chinafactcheck
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [x] 新的路由 New Route
  - [x] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [x] 文档说明 Documentation
  - [x] 中文文档 CN
  - [ ] 英文文档 EN
- [x] 全文获取 fulltext
  - [x] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [x] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

## 说明 / Note

有据|国际新闻事实核查

### CODE REVIEW

**Comment by TonyRL** [comment]
FYI, WordPress-powered site has its RSS feed under `/feed` and REST API under `/wp-json` endpoint

**Comment by kdanfly** [comment]
> FYI, WordPress-powered site has its RSS feed under `/feed` and REST API under `/wp-json` endpoint

Gotcha! My mistake, but the radar does not recognize at the same time. This site is missing the `link` type of `application/rss+xml` to show it's feed link.

**Comment by kdanfly** [comment]
Please check `https://rsshub.app/chinafactcheck`

It's not working without `/` ending, and there is no cache this time. Maybe route under `v2` mast have `/` ending.

**Comment by TonyRL** [comment]
>  and there is no cache this time

That's not true. Maybe I didn't explain it clearly last time:

First, rsshub.app consists of multiple instances and their code are passively synced with GitHub hourly. Meanwhile, docs.rsshub.app is in sync with GitHub utilising the `push` event and built within 5 mins right after `push` is triggered.

Second, demo instances use both Redis and Cloudflare for caching. You can confirm this by
```shell
curl -I https://rsshub.app/chinafactcheck
```

Third, on docs.rsshub.app, you can see a `status up` or a `status down` badge. This is done by checking the response code from the defined example using rsshub.app in real-time (Note that Cloudflare will cache the response from rsshub.app including 404s).

Fourth, there be a notification when a new route is pushed in [@awesomeRSSHub](https://t.me/awesomeRSSHub) Telegram Channel which people will visit the docs for new routes.

As a result, new routes(which should follow v2 standard) like `/chinafactcheck` do not work on demo instances right after it comes out. Adding a `/` will work because it's an unseen request for Cloudflare.

**Pull request merged**
