### PR TITLE
feat(route): add greasyfork script version history and script feedback

### LINKED ISSUE #10597: 🔴 Greasy Fork｜单个脚本的更新通知
### 类型

程序更新

### 网站地址

https://greasyfork.org/zh-CN/scripts/14178-ac-baidu-%E9%87%8D%E5%AE%9A%E5%90%91%E4%BC%98%E5%8C%96%E7%99%BE%E5%BA%A6%E6%90%9C%E7%8B%97%E8%B0%B7%E6%AD%8C%E5%BF%85%E5%BA%94%E6%90%9C%E7%B4%A2-favicon-%E5%8F%8C%E5%88%97/versions

## Greasy Fork｜单个脚本的更新

https://greasyfork.org/zh-CN/scripts/14178-ac-baidu-%E9%87%8D%E5%AE%9A%E5%90%91%E4%BC%98%E5%8C%96%E7%99%BE%E5%BA%A6%E6%90%9C%E7%8B%97%E8%B0%B7%E6%AD%8C%E5%BF%85%E5%BA%94%E6%90%9C%E7%B4%A2-favicon-%E5%8F%8C%E5%88%97/versions

## Greasy Fork｜单个脚本的更新

SCR-20220824-u8m

### 额外描述

+ 目前的 Greasy Fork：https://docs.rsshub.app/program-update.html#greasy-fork 是针对所有脚本的

+ 希望添加支持单个脚本的更新通知

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

### LINKED ISSUE #10598: 🔴 Greasy Fork｜单个脚本的反馈（评论区）
### 类型

程序更新

### 网站地址

https://greasyfork.org/zh-CN/scripts/14178-ac-baidu-%E9%87%8D%E5%AE%9A%E5%90%91%E4%BC%98%E5%8C%96%E7%99%BE%E5%BA%A6%E6%90%9C%E7%8B%97%E8%B0%B7%E6%AD%8C%E5%BF%85%E5%BA%94%E6%90%9C%E7%B4%A2-favicon-%E5%8F%8C%E5%88%97/feedback

## Greasy Fork｜单个脚本的反馈（评论区）

https://greasyfork.org/zh-CN/scripts/14178-ac-baidu-%E9%87%8D%E5%AE%9A%E5%90%91%E4%BC%98%E5%8C%96%E7%99%BE%E5%BA%A6%E6%90%9C%E7%8B%97%E8%B0%B7%E6%AD%8C%E5%BF%85%E5%BA%94%E6%90%9C%E7%B4%A2-favicon-%E5%8F%8C%E5%88%97/feedback

## Greasy Fork｜单个脚本的反馈（评论区）

SCR-20220824-uch

### 额外描述

+ 现在只有全部脚本的更新路由：https://docs.rsshub.app/program-update.html#greasy-fork

+ 没有关于单个脚本反馈（评论区）的路由

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

### PR DESCRIPTION
**Pull request by miles170**
## 该 PR 相关 Issue / Involved issue

Close #10597
Close #10598

## 完整路由地址 / Example for the proposed route(s)

```routes
/greasyfork/scripts/14178-ac-baidu-重定向优化百度搜狗谷歌必应搜索-favicon-双列/versions
/greasyfork/scripts/14178-ac-baidu-重定向优化百度搜狗谷歌必应搜索-favicon-双列/feedback
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [x] 新的路由 New Route
  - [x] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [x] 文档说明 Documentation
  - [x] 中文文档 CN
  - [x] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [x] 可以解析 Parsed
  - [x] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

### CODE REVIEW

**Review by TonyRL — COMMENTED** [review]
`https://greasyfork.org/scripts/14178/versions` and `https://greasyfork.org/scripts/14178/feedback` will work

**Comment by miles170** [comment]
> `https://greasyfork.org/scripts/14178/versions` and `https://greasyfork.org/scripts/14178/feedback` will work

Indeed, should I change the routes?

**Comment by TonyRL** [comment]
> > `https://greasyfork.org/scripts/14178/versions` and `https://greasyfork.org/scripts/14178/feedback` will work
> 
> Indeed, should I change the routes?

Why not, since `lang` isn't necessary. Besides that, there's also a JSON endpoint for version info https://greasyfork.org/scripts/14178/versions.json

**Comment by miles170** [comment]
> > > `https://greasyfork.org/scripts/14178/versions` and `https://greasyfork.org/scripts/14178/feedback` will work
> > 
> > 
> > Indeed, should I change the routes?
> 
> Why not, since `lang` isn't necessary. Besides that, there's also a JSON endpoint for version info https://greasyfork.org/scripts/14178/versions.json

Unfortunately, the JSON endpoint for version info does not have a changelog.

I think we should still grab data from the HTML webpage.

**Comment by miles170** [comment]
> Successfully [generated](https://github.com/DIYgod/RSSHub/actions/runs/2968273502) as following:
> 
> http://localhost:1200/greasyfork/zh-CN/14178-ac-baidu-重定向优化百度搜狗谷歌必应搜索-favicon-双列/versions - Failed
> http://localhost:1200/greasyfork/zh-CN/14178-ac-baidu-重定向优化百度搜狗谷歌必应搜索-favicon-双列/feedback - Failed

I forgot to change the pr routes before pushing comment.
How do I make the bot run a route test again?

**Pull request merged**
