### PR TITLE
fix(route): sichuan/deyang 政府公开信息 

### PR DESCRIPTION
**Pull request by zytomorrow**
## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/gov/sichuan/deyang/govpulicinfo/绵竹市
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [ ] 新的路由 New Route
  - [ ] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [x] 文档说明 Documentation
  - [x] 中文文档 CN
  - [ ] 英文文档 EN
- [x] 全文获取 fulltext
  - [x] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [x] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

## 说明 / Note
日期比对出错进行修改。应该使用`getUTCDate()`而非`getUTCDay()`。
关于UTC时间，比对目标日期直接使用UTC时间，获取的日期写在了正文里，省去转换步骤，直接`目标日期（UTC）-1`即可。
境外IP使用浏览器访问会触发一次503，而后正常，目前代码无法实现。（有一次token换取cookie信任的步骤）

image

### CODE REVIEW

**Comment by Rongronggg9** [comment]
> 境外IP使用浏览器访问会触发一次503，而后正常，目前代码无法实现。

Hint: get cookies from response headers (`set-cookie`), then cache them into the cache. Afterward, all requests should bring the cached cookies.

**Comment by zytomorrow** [comment]
主要是token获取不了，无法找到其生成原理。
用puppeteer获取的话其实可以试试。

**Comment by Rongronggg9** [comment]
> 主要是token获取不了，无法找到其生成原理。 用puppeteer获取的话其实可以试试。

Requests from some regions (in my test, Singapore, Hong Kong) can pass the check with only `__yjs_duid` set, while requests from some other regions cannot...

**Comment by zytomorrow** [comment]
when I disable the IPv6 in my vps(USA),it also can't pass it.The website muse need the `yjs_js_security_passport`,and  I can't get `yjs_js_security_passport`,because  it's set by `https://www.mz.gov.cn/yjs-cgi/security/js_challenge/verify?token=xxxx` with a confusing playload.
截屏2022-04-06 22 06 23
截屏2022-04-06 22 07 22

**Comment by Rongronggg9** [comment]
> when I disable the IPv6 in my vps(USA),it also can't pass it.

I mean, the first request (to get `__yjs_duid`) was sent over IPv4, the second request (with `__yjs_duid` set and passed the check) was sent over IPv6. Actually, as long as the request is sent over IPv6, no need to set cookies to pass the check.

SG VPS:
```
$ curl "https://www.mz.gov.cn/info/iList.jsp?tm_id=1805&cur_page=" -I -6
HTTP/2 200
cache-control: no-cache
content-type: text/html;charset=utf-8
date: Wed, 06 Apr 2022 14:15:51 GMT
expires: Wed, 31 Dec 1969 23:59:59 GMT
pragma: no-cache
server: yunjiasu
set-cookie: __yjs_duid=<REDACTED>; expires=Fri, 05-Apr-24 14:15:51 GMT; Path=/; Domain=mz.gov.cn; HttpOnly; Secure
set-cookie: JSESSIONID=<REDACTED>; Path=/; HttpOnly
vary: Accept-Encoding,User-Agent
yjs-id: <REDACTED>
```
```
curl "https://www.mz.gov.cn/info/iList.jsp?tm_id=1805&cur_page=" -I -4
HTTP/2 503
content-type: text/html; charset=UTF-8
date: Wed, 06 Apr 2022 14:19:18 GMT
server: yunjiasu
set-cookie: __yjs_duid=<REDACTED>; expires=Fri, 05-Apr-24 14:19:18 GMT; Path=/; Domain=mz.gov.cn; HttpOnly; Secure
yjs-id: <REDACTED>
```

**Comment by zytomorrow** [comment]
When use ipv4 fail , it will try to use  ipv6 now.my vps  ipv6 don't work good,so I can't test it.I try to use other vps to test tomorrow.
thx.

**Comment by zytomorrow** [comment]
thx.You are right.When enable ipv6,the route can get content.
image

**Pull request merged**
