### PR TITLE
perf(route/reuters): use downsized pictures from Reuters

### PR DESCRIPTION
**Pull request by lewisjiang**
## 该 PR 相关 Issue / Involved Issue

Close #

## 路由地址示例 / Example for the Proposed Route(s)

```routes
/reuters/world
```

## 新 RSS 路由检查表 / New RSS Route Checklist
  
- [ ] 新的路由 New Route
  - [ ] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [ ] 文档说明 Documentation
  - [ ] 中文文档 CN
  - [ ] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

## 说明 / Note

The origal routes for /reuters request raw news pictures, which have sizes up to 5mb each. This means a single refresh of one reuters channel in an RSS reader can easily consume 100+mb data, and extreme lags can be noticed in some readers who do not optimize thumbnails when scrolling. So this pull request fixes the issue by requesting downsized images from Reuters itself. The default long side of each image is limited to 1080px (`1080w` in `/templates/description.art`), which can be adjusted to 60, 120, 240, 480, 960, 1200 and 1920 if you prefer different resolutions.

### CODE REVIEW

**Comment by TonyRL** [comment]
Which RSS reader has extreme lags when scrolling unoptimized thumbnails?

**Comment by lewisjiang** [comment]
@TonyRL [fluent reader](https://github.com/yang991178/fluent-reader) as for my experience.

**Review by TonyRL — COMMENTED** [review]
Please switch to `1920w` so it looks better than `1080w` on those high-resolution screens. It looks like the CDN will serve AVIF (~100kb, 80% quality from 1.88MB) on modern devices and fall back to JPEG (~200kb) on older devices.

**Comment by lewisjiang** [comment]
@TonyRL Done.

**Pull request merged**
