### PR TITLE
feat(route): add CBNData消费站看点

### LINKED ISSUE #7801: 求增加cbndata消费站看点频道
### 网站地址
https://cbndata.com/information
### 网站描述
是由第一财经和阿里巴巴共同发起成立的国内领先的消费大数据研究机构、数据传播服务商和金融资讯运营服务商。
### 需要生成什么内容？
看点频道
### 额外描述
文章质量挺高的，求增加谢谢。

### PR DESCRIPTION
**Pull request by nczitzk**
## 该 PR 相关 Issue / Involved issue

Close #7801

## 完整路由地址 / Example for the proposed route(s)

```routes
/cbndata/information
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [x] 是否支持全文获取? Is this RSS Script support fulltext?
  - [x] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [x] 目标是否有提供日期？ Is there a date in the source?
  - [x] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [x] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason

### CODE REVIEW

**Review by murphysking — APPROVED** [review]
获取详情也可以用 https://www.cbndata.com/api/v3/informations/show?id=[文章id]

**Comment by nczitzk** [comment]
> 获取详情也可以用 [https://www.cbndata.com/api/v3/informations/show?id=[文章id]](https://www.cbndata.com/api/v3/informations/show?id=%5B%E6%96%87%E7%AB%A0id%5D)

👍

**Comment by SettingDust** [comment]
link 不对

**Review by murphysking — APPROVED** [review]

**Review by SettingDust — APPROVED** [review]

**Review by NeverBehave — APPROVED** [review]

**Comment by NeverBehave** [comment]
看来以后得再看仔细点，不然link是undefined都看不出来……

**Pull request merged**
