### PR TITLE
Fix(route): fix route address

### LINKED ISSUE #8941: Epicgames rss failed
### Routes

epicgames/freegames

### Full routes

epicgames/freegames

### Related documentation

https://docs.rsshub.app/game.html#epic-games-store

### What is expected?

Load the rss

### What is actually happening?

Route requested: /epicgames/freegames

Error message: wrong path

Helpful Information to provide when opening issue: 
Path: /epicgames/freegames
Node version: v16.3.0
        

### Deployment information

RSSHub demo (https://rsshub.app)

### Deployment information (for self-hosted)

_No response_

### Additional info

```shell
https://rsshub.app/epicgames/freegames

Document for it is added in 2020
https://github.com/DIYgod/RSSHub/issues/4071

@Zyx-A
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

### PR DESCRIPTION
**Pull request by Fatpandac**
## 该 PR 相关 Issue / Involved issue

Close #8941

## 完整路由地址 / Example for the proposed route(s)

```routes
/epicgames/freegames 
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [X] New Route
- [X] Documentation
  - [X] CN
  - [ ] EN
- [ ] 全文获取 fulltext
  - [ ] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] 日期和时间 date and time
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

### CODE REVIEW

**Comment by hifocus** [comment]
I may not fully understand the mechanism of this fix but the provided deployment `https://rsshub-dncw5ibbp-diy.vercel.app/epicgames/freegames` does seem to be returning 404 still on my end.

```
C:\Users\Huangxin>curl -I https://rsshub-dncw5ibbp-diy.vercel.app/epicgames/freegames
HTTP/1.1 404 Not Found
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
X-Robots-Tag: noindex
cache-control: public, max-age=300
date: Wed, 02 Feb 2022 15:10:28 GMT
access-control-allow-methods: GET
x-content-type-options: nosniff
access-control-allow-origin: rsshub-dncw5ibbp-diy.vercel.app
content-length: 0
x-vercel-cache: MISS
age: 0
server: Vercel
x-vercel-id: lhr1::iad1::fx7vp-1643814627963-79013bce9ff2
strict-transport-security: max-age=63072000; includeSubDomains; preload
```

**Comment by Fatpandac** [comment]
> I may not fully understand the mechanism of this fix but the provided deployment `https://rsshub-dncw5ibbp-diy.vercel.app/epicgames/freegames` does seem to be returning 404 still on my end.
> 
> ```
> C:\Users\Huangxin>curl -I https://rsshub-dncw5ibbp-diy.vercel.app/epicgames/freegames
> HTTP/1.1 404 Not Found
> Content-Type: text/html; charset=UTF-8
> Connection: keep-alive
> X-Robots-Tag: noindex
> cache-control: public, max-age=300
> date: Wed, 02 Feb 2022 15:10:28 GMT
> access-control-allow-methods: GET
> x-content-type-options: nosniff
> access-control-allow-origin: rsshub-dncw5ibbp-diy.vercel.app
> content-length: 0
> x-vercel-cache: MISS
> age: 0
> server: Vercel
> x-vercel-id: lhr1::iad1::fx7vp-1643814627963-79013bce9ff2
> strict-transport-security: max-age=63072000; includeSubDomains; preload
> ```

This is a new bug.
The request address was changed.

**Comment by hifocus** [comment]
> > I may not fully understand the mechanism of this fix but the provided deployment `https://rsshub-dncw5ibbp-diy.vercel.app/epicgames/freegames` does seem to be returning 404 still on my end.
> > ```
> > C:\Users\Huangxin>curl -I https://rsshub-dncw5ibbp-diy.vercel.app/epicgames/freegames
> > HTTP/1.1 404 Not Found
> > Content-Type: text/html; charset=UTF-8
> > Connection: keep-alive
> > X-Robots-Tag: noindex
> > cache-control: public, max-age=300
> > date: Wed, 02 Feb 2022 15:10:28 GMT
> > access-control-allow-methods: GET
> > x-content-type-options: nosniff
> > access-control-allow-origin: rsshub-dncw5ibbp-diy.vercel.app
> > content-length: 0
> > x-vercel-cache: MISS
> > age: 0
> > server: Vercel
> > x-vercel-id: lhr1::iad1::fx7vp-1643814627963-79013bce9ff2
> > strict-transport-security: max-age=63072000; includeSubDomains; preload
> > ```
> 
> This is a new bug. The request address was changed.

Hope you are able to fix this soon. Thanks so much for the work.

**Comment by TonyRL** [comment]
The new GraphQL endpoint is `https://www.epicgames.com/graphql`

**Pull request merged**
