### PR TITLE
fix(config): debug not shown when DEBUG_INFO set true

### PR DESCRIPTION
**Pull request by tuzi3040**
## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
NOROUTE
```

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [ ] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

Debug info is not shown when DEBUG_INFO is set to 'true'.

### CODE REVIEW

**Review by NeverBehave — CHANGES_REQUESTED** [review]
Could you also change the default value in `config.js`? it is using false instead of 'false'

**Comment by tuzi3040** [comment]
> Could you also change the default value in `config.js`? it is using false instead of 'false'

You do understand changing boolen `false` to string `'false'` has no effect on the final result, right?
And you request this change just for code style?
I just want to make sure we are on the same page.

**Comment by NeverBehave** [comment]
> > Could you also change the default value in `config.js`? it is using false instead of 'false'
> 
> You do understand changing boolen `false` to string `'false'` has no effect on the final result, right?
> And you request this change just for code style?
> I just want to make sure we are on the same page.

Even though js is weak type language here, this option is defined as a string and we keep its type the same here. 
It is also a tip when people reading the config file knowing it is a string option rather than a boolean.

**Comment by tuzi3040** [comment]
> > > Could you also change the default value in `config.js`? it is using false instead of 'false'
> > 
> > 
> > You do understand changing boolen `false` to string `'false'` has no effect on the final result, right?
> > And you request this change just for code style?
> > I just want to make sure we are on the same page.
> 
> Even though js is weakly typed language here, this option is defined as a string and we keep its type the same here.
> It is also a tip when people reading the config file knowing it is a string option rather than a boolean.
> tbh, I am confused at first.

Done.

**Comment by DIYgod** [comment]
a0dd6756dad5b682e88863400c594d402a26e19f 6506c39239e5bd35a27889d92d46acca9a048c63 I have reset the default value of debugInfo to true, and remove `hot ip`, so maybe this pr is no longer needed

**Comment by NeverBehave** [comment]
If the inconsistency doesn't matter (true and 'false'), this pr could be closed.

**Comment by tuzi3040** [comment]
> a0dd6756dad5b682e88863400c594d402a26e19f 6506c39239e5bd35a27889d92d46acca9a048c63 I have reset the default value of debugInfo to true, and remove `hot ip`, so maybe this pr is no longer needed

Though the default value has been reset to `true` now, when DEBUG_INFO set to string `'true'`, route info is not always displayed. Which requires `?debug=true` instead, may be confusable. But it seems intentional in comment.
And what about use NODE_ENV to control hot ip display, like detailed error output requires NODE_ENV not `'production'`.

**Comment by DIYgod** [comment]
> Though the default value has been reset to `true` now, when DEBUG_INFO set to string `'true'`, route info is not always displayed. Which requires `?debug=true` instead, may be confusable. But it seems intentional according to comment?...
> And what about use NODE_ENV to control hot ip display, like detailed error output requires NODE_ENV not `'production'`.

You are right, I merged your changes 1a463e09c99c1c70b66adad43b950a9241d09c09

As for controlling the IP display, I think there are privacy issues, it would be better to remove it completely, the owner should view it through the backend logs instead.

**Comment by tuzi3040** [comment]
> You are right, I merged your changes [1a463e0](https://github.com/DIYgod/RSSHub/commit/1a463e09c99c1c70b66adad43b950a9241d09c09)

thx
> As for controlling the IP display, I think there are privacy issues, it would be better to remove it completely, the owner should view it through the backend logs instead.

That's true. I agree with you.
I'll close this pr now.

**Pull request closed without merging**
