### PR TITLE
fix(route/weibo/*): sinaimg anti-hotlinking

### PR DESCRIPTION
**Pull request by Rongronggg9**
## 该 PR 相关 Issue / Involved issue

https://github.com/DIYgod/RSSHub/issues/11096#issuecomment-1325061604

## 完整路由地址 / Example for the proposed route(s)

```routes
/weibo/user/1195230310
/weibo/keyword/DIYgod
/weibo/super_index/1008084989d223732bf6f02f75ea30efad58a9/sort_time
```

Unable/No need to test:
```
/weibo/search/hot
/weibo/timeline/3306934123
/weibo/oasis/user/1990895721
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [ ] 新的路由 New Route
  - [ ] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [ ] 文档说明 Documentation
  - [ ] 中文文档 CN
  - [ ] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

### CODE REVIEW

**Comment by dabo-t** [comment]
不建议做这样的处理。部分图片替换后会无法显示。

**Comment by Rongronggg9** [comment]
> 不建议做这样的处理。部分图片替换后会无法显示。

Ref? Example?

**Comment by dabo-t** [comment]
> 

微博：https://weibo.com/5542384916/MdWSsfgMw?type=comment#_rnd1669272420048
第四张图11月7日抓下来的链接是https://wx3.sinaimg.cn/large/00635hv6ly1h7wrmvxitvaj30u0140q8t.jpg  替换成tva3无法显示
image

现在抓下来变成了00635hv6ly1h7wrmvxiwxj30u0140q8t

**Comment by Rongronggg9** [comment]
> > 
> 
> 微博：[weibo.com/5542384916/MdWSsfgMw?type=comment#_rnd1669272420048](https://weibo.com/5542384916/MdWSsfgMw?type=comment#_rnd1669272420048) 第四张图11月7日抓下来的链接是[wx3.sinaimg.cn/large/00635hv6ly1h7wrmvxitvaj30u0140q8t.jpg](https://wx3.sinaimg.cn/large/00635hv6ly1h7wrmvxitvaj30u0140q8t.jpg) 替换成tva3无法显示 image
> 
> 现在抓下来变成了00635hv6ly1h7wrmvxiwxj30u0140q8t

Obviously, it is NOT a CDN-relevant issue. It's expired, and so is the `wx3` URL. Your instance exactly indecates that there is NO difference between `wx[1-4]` URLs and `tvax?[1-4]` ones, except for referer policy, with which is what we are concerned mostly.

```console
$ curl -I 'https://wx3.sinaimg.cn/large/00635hv6ly1h7wrmvxitvaj30u0140q8t.jpg' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0' -H 'Accept: image/avif,image/webp,*/*' -H 'Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2' -H 'Accept-Encoding: gzip, deflate, br' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Referer: https://weibo.com/' -H 'Sec-Fetch-Dest: image' -H 'Sec-Fetch-Mode: no-cors' -H 'Sec-Fetch-Site: cross-site' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'TE: trailers'
HTTP/2 302
server: Tengine
content-type: text/html
content-length: 145
x-uidblock-version: 18369
x-ban: miss,18369
date: Thu, 24 Nov 2022 07:03:33 GMT
cache-control: max-age=3
x-error-type: notexists
x-request-id: g75.122-1669273413.139000-2317223454
location: //gzw.sinaimg.cn/images/default_w_large.gif#104
edge-copy-time: 1669273413145
via: http/1.1 cnc.guangzhou.union.67 (ApacheTrafficServer/6.2.1 [cSsSfU]), cache13.l2cn1837[49,49,302-0,M], cache56.l2cn1837[35:51,0], cache56.l2cn1837[86,0], vcache21.cn4671[106,106,302-0,M], vcache2.cn4671[109,0]
x-via-cdn: f=alicdn,s=vcache2.cn4671,c=123.52.16.153;f=edge,s=cnc.guangzhou.union.58.nb.sinaedge.com,c=119.36.0.235;f=Edge,s=cnc.guangzhou.union.67,c=172.16.116.58
x-via-edge: 1669273413145eb0024773a7410ac47822596
edgetc: 0
ali-swift-global-savetime: 1669273413
x-swift-savetime: Thu, 24 Nov 2022 07:03:33 GMT
x-swift-cachetime: 0
age: 0
x-cache: MISS TCP_MISS dirn:-2:-2
x-swift-savetime: Thu, 24 Nov 2022 07:03:33 GMT
x-swift-cachetime: 0
access-control-allow-credentials: true
timing-allow-origin: *
eagleid: b7c9dc1616692734130523501e
```

**Comment by Rongronggg9** [comment]
@dabo-t OK, then. I re-checked your reply, not very sure what did you mean.

Did you mean my regex is mistaken?
```
https://wx3.sinaimg.cn/large/00635hv6ly1h7wrmvxitvaj30u0140q8t.jpg
                                                ^^^
                             00635hv6ly1h7wrmvxiwxj30u0140q8t
                                                ^^
```

But it is not.
```js
> const regex = /(?<=\/)wx(?=[1-4]\.sinaimg\.cn\/)/gi;
undefined
> 'https://wx3.sinaimg.cn/large/123wxwx456tva.jpg'.replace(regex, 'tva')
'https://tva3.sinaimg.cn/large/123wxwx456tva.jpg'
```

**Comment by ruleroller** [comment]
@TonyRL 如果没问题的话，是否可以抽空通过一下下呀？快一周看不到图片了……

**Comment by ruleroller** [comment]
大佬们好，微博图片又开始403了，唉。

**Comment by Rongronggg9** [comment]
> 大佬们好，微博图片又开始403了，唉。

Unreproducible.

**Comment by ruleroller** [comment]
@Rongronggg9 更新了之后，正常了一天，下午开始好像又不能显示图片了。无尽战争嘛。。。

**Comment by Rongronggg9** [comment]
Nothing more I can do.

Refer to https://github.com/DIYgod/RSSHub/issues/10874#issuecomment-1369647937 for more workarounds.

**Pull request merged**
