### PR TITLE
fix(route): get correct item link

### PR DESCRIPTION
**Pull request by x1e5c**
## Involved Issue / 该 PR 相关 Issue

Close #

## Example for the Proposed Route(s) / 路由地址示例

```routes
/rsshub/transform/html/https%3A%2F%2Fllwslc.github.io%2Fgrammar-club%2Fcontent%2FPreface.html/title%3Dgrammar-club%26item%3D%20header%20%3E%20div.links%20%3E%20nav%20%3E%20div%20%26itemLink%3Da
/rsshub/transform/html/https%3A%2F%2Fbionumpy.github.io%2Fbionumpy%2Fmenu.html/itemLink%3Da
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

## Note / 说明

When the `href` link inside the element is a relative link, the original handling would obtain an incorrect full link

This is the official documentation for numpy `https://numpy.org/doc/stable/user/index.html`, where most `a` tags have relative links. Here is the code effect before and after modification based on this site

item href     |    ``` `${new URL(url).origin}${link}` ``` | ``` (new URL(link, url)).href  ```
---- | ----- | -----
`whatisnumpy.html` |   `https://numpy.orgwhatisnumpy.html`  | `https://numpy.org/doc/stable/user/whatisnumpy.html`
`../reference/index.html#reference` |  `https://numpy.org../reference/index.html#reference` |  `https://numpy.org/doc/stable/reference/index.html#reference`

### CODE REVIEW

**Review by TonyRL — COMMENTED** [review]
Please do provide an example for testing

**Comment by x1e5c** [comment]
@TonyRL 

> Please do provide an example for testing

This is the official documentation for numpy `https://numpy.org/doc/stable/user/index.html`, where most `a` tags have relative links. Here is the code effect before and after modification based on this site

item href     |    ``` `${new URL(url).origin}${link}` ``` | ``` (new URL(link, url)).href  ```
---- | ----- | -----
`whatisnumpy.html` |   `https://numpy.orgwhatisnumpy.html`  | `https://numpy.org/doc/stable/user/whatisnumpy.html`
`../reference/index.html#reference` |  `https://numpy.org../reference/index.html#reference` |  `https://numpy.org/doc/stable/reference/index.html#reference`

**Comment by TonyRL** [comment]
Please fill in the example in the PR template.

**Comment by TonyRL** [comment]
I should make it clearer next time.

Please fill in the `Example for the Proposed Route(s) / 路由地址示例` in the PR template for testing.

**Pull request merged**
