### PR TITLE
feat(route/thepaper): Allow to use PC link.

### PR DESCRIPTION
**Pull request by dzx-dzx**
## Involved Issue / 该 PR 相关 Issue

Close #

## Example for the Proposed Route(s) / 路由地址示例

```routes
/thepaper/featured?pc=yes
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

### CODE REVIEW

**Review by TonyRL — COMMENTED** [review]
`https://m.thepaper.cn/detail/${item.contId}` works fine with `/thepaper/featured`

**Comment by dzx-dzx** [comment]
> `https://m.thepaper.cn/detail/${item.contId}` works fine with `/thepaper/featured`

Well... Just another choice?

**Review by TonyRL — COMMENTED** [review]
With the above changes, it:
- allows cache storing the same feed item with different key
- breaks guid

**Comment by dzx-dzx** [comment]
> With the above changes, it:
> 
>     * allows cache storing the same feed item with different key
> 
>     * breaks guid

No guid is included for the first place, and...technically, two different links aren't the same feed item?

**Comment by zhoxiaoqiang** [comment]
What?

**Pull request closed without merging**
