### PR TITLE
fix(route/twitter): Web API authentication

### LINKED ISSUE #12732: Twitter user timeline cannot be crawled (possibly related to restrictions on non-registered users)
### 路由地址

```routes
/twitter/user/:id/:routeParams?
```

### 完整路由地址

```fullroutes
/twitter/user/garrulous_abyss
```

### 相关文档

https://docs.rsshub.app/social-media.html#twitter-yong-hu-shi-jian-xian

### 预期是什么？

正常返回 feed

### 实际发生了什么？

Looks like something went wrong

Route requested: /user/garrulous_abyss

Error message: Response code 404 (Not Found): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.

Helpful Information to provide when opening issue:
Path: /user/garrulous_abyss
Node version: v18.16.1
Git Hash: 7775ee5

### 部署

自建

### 部署相关信息

OS: Linux, Node: v18.16.1

### 额外信息

```shell
疑似原因：蓝鸟平台限制了非注册用户访问。例如访问 https://twitter.com/XenoPanther 会被跳转到 https://twitter.com/i/flow/login?redirect_after_login=%2FXenoPanther

相关报道 https://www.theverge.com/2023/6/30/23779764/twitter-blocks-unregistered-users-account-tweets
该报道认为此变化是马斯克有意为之

    Several hundred organizations (maybe more) were scraping Twitter data extremely aggressively, to the point where it was affecting the real user experience.

    What should we do to stop that? I’m open to ideas.
    — Elon Musk (@elonmusk) June 30, 2023
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by Rongronggg9**
## 该 PR 相关 Issue / Involved Issue

Close #12732

## 路由地址示例 / Example for the Proposed Route(s)

```routes
/twitter/tweet/DIYgod/status/1650844643997646852
/twitter/user/bugcat_capoo_tw
/twitter/user/bugcat_capoo_tw/excludeReplies=1
```

## 新 RSS 路由检查表 / New RSS Route Checklist
  
- [ ] 新的路由 New Route
  - [ ] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [ ] 文档说明 Documentation
  - [ ] 中文文档 CN
  - [ ] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

## 说明 / Note
Special thanks to https://github.com/zedeus/nitter/issues/919#issuecomment-1619067142
Currently still no way to search without logging in, so the `keyword` route has not been fixed.

### CODE REVIEW

**Comment by DIYgod** [comment]
You are incredibly fast!

**Comment by Rongronggg9** [comment]
> Currently still no way to search without logging in, so the keyword route has not been fixed.

Oh, it seems that, though, not working in my local test (403 Forbidden), the existing approach works fine on the public demo after applying my patch! 
https://rsshub.app/twitter/keyword/RSSHub?forceWebApi=1

**Comment by nonemo13** [comment]
Looks like need to fix images small typo: `?format=jpg&amp;name=orig`

**Comment by Rongronggg9** [comment]
> > Currently still no way to search without logging in, so the keyword route has not been fixed.
> 
> Oh, it seems that, though, not working in my local test (403 Forbidden), the existing approach works fine on the public demo after applying my patch! 
>  https://rsshub.app/twitter/keyword/RSSHub?forceWebApi=1

Hmm, I made a mistake, `s#?#/#g`, making the usage of developer API not forbidden. So there is still no way to search without logging in or a developer API key. But the v1 developer API keeps working? Interesting to know.

**Comment by Rongronggg9** [comment]
> Looks like need to fix images small typo: `?format=jpg&amp;name=orig`

It is not a typo but HTML escape

**Comment by jkryanchou** [comment]
@Rongronggg9 I have ran the latest RSSHub while raise the exception as below 
```
You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product (Twitter code 453)
    at RequestHandlerHelper.createResponseError (/home/ubuntu/RSSHub/node_modules/twitter-api-v2/dist/cjs/client-mixins/request-handler.helper.js:103:16)
    at RequestHandlerHelper.onResponseEndHandler (/home/ubuntu/RSSHub/node_modules/twitter-api-v2/dist/cjs/client-mixins/request-handler.helper.js:252:25)
    at Gunzip.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Pull request merged**
