### PR TITLE
feat: Add new router and fix bug (nature/science journals cover story... etc) 

### PR DESCRIPTION
**Pull request by yech1990**
### add new router

- new router for nature journal cover story 📚
- new router for Science journal cover story 📚

### enhance

- increase font size nature journals (the original style is difficult to read) 
- some useful message for pnas journal
- remove constrain of fetch items number in nature news
- update documentation

### CODE REVIEW

**Comment by yech1990** [comment]
preview for cover story:

image

image

**Comment by yech1990** [comment]
preview science cover:

image

image

**Comment by yech1990** [comment]
more useful message with reading experience improved

image

image

**Comment by DIYgod** [comment]
貌似跟 #4094 有较多冲突，方便解决一下冲突么？

**Comment by yech1990** [comment]
@DIYgod #4094 aim to add a simple function into the for science journals, but create chaos for the project.

- A gobal env, `envs.SCIHUB_HOST`, was created but never used elsewhere.
- New journal folder increases the difficulty of debugging and also creates logical conflicts. eg, x-mol is located in journal folder/section, but one of its router is documented in the study section.
- Scihub support badge has been added into some routers, but only several of them has `doi` parameter, which is essential for Scihub support.
- The several websites involved are comprehensive websites, in addition to journals, there are also some historical, job-seeking sections.

I tried to fix several bugs, but its main features are still reserved. I feel regretful for merging  #4094 without thorough discussion, but thanks HenryQW for his contribution.

**Comment by DIYgod** [comment]
我不是很能理解这些网站之间的关系...可能要找个时间好好看下，在这之前 @HenryQW 可以解释下上述几个问题？

**Comment by HenryQW** [comment]
@yech1990 1. global env is not required and doesn’t not affect any of existing routes.

1.How so? 理想化的目录结构难道不应该是，所有文档section有自己对应的目录。

1. scihub 支持 high impact factor 期刊的URL，无需DOI。
所有带badge的路由我都亲自测试过。

1.

**Comment by yefoenix** [comment]
@yech1990 在 RSSHub 中，gobal env 会被用来对某些模块进行针对性配置，可参考 https://docs.rsshub.app/install/#bu-fen-rss-mo-kuai-pei-zhi ，不需要 used elsewhere.
鉴于 sci-hub.tw 这个域名的可访问性很不稳定，且 Sci-hub 也有更换主域名的可能，增加这个环境变量还是有必要的。

**Pull request merged**
