### PR TITLE
chore: bump pnpm lockfile

### PR DESCRIPTION
**Pull request by HenryQW**
## Involved Issue / 该 PR 相关 Issue

Close #

## Example for the Proposed Route(s) / 路由地址示例

```routes
NOROUTE
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

## Note / 说明

lockfile v6 is deprecated by pnpm v9, and is now readonly.

https://github.com/pnpm/pnpm/issues/7934

### CODE REVIEW

**Comment by HenryQW** [comment]
> https://github.com/DIYgod/RSSHub/blob/936e7032d286dfb4614a276816c8dadd045ad0aa/.github/workflows/build-assets.yml#L25-L27
> 
> 
> GitHub actions also need to be bumped.

Done. I think current CIs are way too complicated, we might want to simplify them.

**Comment by HenryQW** [comment]
> Dependabot is still having minor issue with pnpm v9 [dependabot/dependabot-core#9522](https://github.com/dependabot/dependabot-core/issues/9522) though.

dependabot is really slow in adopting these major changes, which is very annoying, but I think it is solved? https://github.com/dependabot/dependabot-core/pull/9668

**Comment by TonyRL** [comment]
@DIYgod Can you enable **Dependabot on Actions runners** in https://github.com/DIYgod/RSSHub/settings/security_analysis too?

**Comment by DIYgod** [comment]
@TonyRL Now it is opened

**Pull request merged**
