### PR TITLE
feat: pixiv bookmarks rss

### PR DESCRIPTION
**Pull request by EYHN**
pixiv 用户收藏 rss

image

（暗中观察

### CODE REVIEW

**Comment by EYHN** [comment]
Close #86

**Comment by DIYgod** [comment]
路由 `/pixiv/user/:id/bookmarks` 建议改为 `/pixiv/user/bookmarks/:id`

**Comment by EYHN** [comment]
@DIYgod changed

**Comment by whtsky** [comment]
#77

**Pull request merged**
