### PR TITLE
增加看雪论坛外文翻译版块rss

### PR DESCRIPTION
**Pull request by CitrusIce**
## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

http://127.0.0.1:1200/pediy/topic/translate

### CODE REVIEW

**Review by NeverBehave — CHANGES_REQUESTED** [review]
https://rsshub-git-fork-citrusice-master.diy.now.sh/pediy/topic/translate
Not working.

**Comment by CitrusIce** [comment]
it seems like a network problem that the server can not access the bbs.pediy.com. Accessing routes of other board of the forum （such as https://rsshub-git-fork-citrusice-master.diy.now.sh/pediy/topic/re） will also get a "502: BAD_GATEWAY"

**Comment by NeverBehave** [comment]
It looks like page load taking too much time. I think it should be fine for now.

**Comment by NeverBehave** [comment]
Oops I forgot... Could you please make another PR add the docs?

**Comment by CitrusIce** [comment]
sure

**Pull request merged**
