### PR TITLE
Update keyword.js

### PR DESCRIPTION
**Pull request by yuanotes**
add limits filter to weibo keyword source

### CODE REVIEW

**Comment by yuanotes** [comment]
目前的关键字内容太水，没法看

**Comment by yuanotes** [comment]
或者我加个粉丝数过滤

**Comment by DerekTso** [comment]
@DIYgod @yuanotes when one weibo update comes in, make a delay, say, 10mins, then begin to fetch those info as a rss feed. is it ok to create a delay middleware for that case? just my assumption.

**Comment by DIYgod** [comment]
内容太水属于数据源的问题，这样过滤意义不大

**Pull request closed without merging**
