### PR TITLE
feat(route): add eventernote

### PR DESCRIPTION
**Pull request by KTachibanaM**
## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/eventernote/actors/三森すずこ/2634
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [x] New Route
- [ ] Documentation
  - [x] CN
  - [ ] EN
- [ ] 全文获取 fulltext
  - [ ] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] 日期和时间 date and time
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

### CODE REVIEW

**Comment by TonyRL** [comment]
Please use v2 script standard https://github.com/DIYgod/RSSHub/discussions/8236

**Comment by KTachibanaM** [comment]
Hi, this PR is ready for review, but I am not sure why the CI is failing..?

**Comment by TonyRL** [comment]
`[docker] CI for build tests` is failing because https://github.com/DIYgod/RSSHub/pull/8716 hasn't been merged yet

**Comment by KTachibanaM** [comment]
> `[docker] CI for build tests` is failing because #8716 hasn't been merged yet

Is it possible to review and get this MR merged then? Looks like the activity on #8716 is stale.

**Comment by KTachibanaM** [comment]
Hello, I've merged #8716 into my branch. Can you please take another look? Thank you.

**Review by TonyRL — APPROVED** [review]

**Pull request merged**
