### PR TITLE
fix: Instagram carousel exception

### PR DESCRIPTION
**Pull request by oppilate**
## 该 PR 相关 Issue / Involved 
- Not compatible with vercel.app. Not possible to login (because of variable's lifecycle?)
- Carousel caused exception

## 完整路由地址 / Example for the proposed route(s)

`/instagram/user/ladygaga`

### CODE REVIEW

**Comment by oppilate** [comment]
In the latest commit, hopefully it's possible to save the login status for non-vercel environments and login at every request on vercel.app

**Comment by oppilate** [comment]
Sorry, don't know how to fix that DeepScan complaint

**Comment by oppilate** [comment]
"Solved" by disabling that complaint.

**Comment by HenryQW** [comment]
Actually, the compatibility with vercel is not required, you don't have to preserve the login status.

**Comment by proletarius101** [comment]
Well, but I use it there... Because it's faster and free.

**Comment by oppilate** [comment]
Well, but I use it there :rofl:  It's faster and free. And why not?

**Comment by oppilate** [comment]
And interestingly, the build fails. But I didn't touch anything in `./docs/game.md`?

**Comment by HenryQW** [comment]
> And interestingly, the build fails. But I didn't touch anything in `./docs/game.md`?

That was something else in the master which was fixed.



> Well, but I use it there 🤣  It's faster and free. And why not?

It's tricky to test that out, I will have to revisit this another day.

**Comment by oppilate** [comment]
> you don't have to preserve the login status.

And, to prevent misunderstanding, Vercel is more request-based which means it needs to login per request. On docker or other type of deplyments, it only needs one login per app session.

**Pull request merged**
