### PR TITLE
fix(route)(wechat/ershicimi): outdated URL

### LINKED ISSUE #7911: 二十次幂网址变了，不能再获取微信订阅，能否更新路由
### 这是一个什么样的功能？
二十次幂网址变更，能否更新路由
### 这个功能可以解决什么问题？
网址变更后似乎原来的路由不能用了
原路由：/wechat/ershicimi/:id
### 额外描述
原网址：https://www.ershicimi.com/
现网址：https://www.cimidata.com/

### PR DESCRIPTION
**Pull request by Rongronggg9**
## 该 PR 相关 Issue / Involved issue

Close #7911

## 完整路由地址 / Example for the proposed route(s)

```routes
/wechat/ershicimi/813oxJOl
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [ ] 新的路由 New Route
  - [ ] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [ ] 文档说明 Documentation
  - [ ] 中文文档 CN
  - [ ] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

### CODE REVIEW

**Comment by TonyRL** [comment]
Just a side note to the utility: 
Looks like the search params of `chksm` and `scene` can be safely removed and we can still retrieve the article.

**Comment by TonyRL** [comment]
Just a side note to the utility: 
Looks like the search params of `chksm` and `scene` can be safely removed and we can still retrieve the article.

**Comment by Rongronggg9** [comment]
> Just a side note to the utility: Looks like the search params of `chksm` and `scene` can be safely removed and we can still retrieve the article.

I've also noticed that but thanks for your reminder. Later I will open another PR.

**Comment by Rongronggg9** [comment]
I consider there are two reasons why we don't need to keep `item.guid`:
1. the former one is like `https://www.ershicimi.com/...`, now it is like `https://mp.weixin.qq.com/...`
2. The route has been broken for a long time

so 1ae96a2

**Pull request merged**
