### PR TITLE
Scmp series

### PR DESCRIPTION
**Pull request by oppilate**
## 该 PR 相关 Issue / Involved issue

Depends on  #6444

## 完整路由地址 / Example for the proposed route(s)

`/scmp/318198`

There's an item with link containing `series`. It would break the feed. This patch fixes the problem.

### CODE REVIEW

**Comment by HenryQW** [comment]
This PR should not include the UA changes.

**Comment by oppilate** [comment]
Unfortuatenly there's a change of the UA variable. So it has to include the UA change or if the UA change is rejected it has to rollback that part.

**Comment by NeverBehave** [comment]
Hi, I believe we may have to separate these two: as the UA changes won't come in the short time. 

If you still want to land the rss changes, it may have to done in the "ugly" way for now. Please advise.

**Comment by oppilate** [comment]
Sure. Since the ua issue stucks, this issue should not depend on that anymore. Will do the job tomorrow.

**Comment by NeverBehave** [comment]
> Sure. Since the ua issue stucks, this issue should not depend on that anymore. Will do the job tomorrow.

Cool, I will close this pr for now. open a new one when finished.

**Pull request closed without merging**
