### PR TITLE
refactor: timezone conversion in `lib/utils/date.js`

### LINKED ISSUE #6795: pubDate 时间错误
#### 路由地址（不包含参数）

```
/ifnews/:cid
```

#### 完整路由地址，包含所有必选与可选参数

```
https://rsshub.app/ifnews/40
```

#### 相关文档地址

- https://docs.rsshub.app/traditional-media.html#ren-min-ri-bao

#### 预期是什么
时间 <pubDate>应该是正确的

#### 实际发生了什么
时间 <pubDate>错误，显示的时间实际是明天
例如：现在时间是北京时间 2021/1/26 16:21
RSS 内有：
lastBuildDate：Tue, 26 Jan 2021 07:30:43 GMT
pubDate：Tue, 26 Jan 2021 23:07:00 GMT

其中，pubDate明显不对，猜测是时间GMT+8 和 GMT-8弄反了，所以 23:07:00实际应该是7:07:00

除了这个路由外，其他很多路由都出现类似问题，例如：
/21caijing/channel/:name
/bjnews/:category
/yicai/brief

#### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

### PR DESCRIPTION
**Pull request by queensferryme**
## 该 PR 相关 Issue / Involved issue

Close #6795 

## 完整路由地址 / Example for the proposed route(s)

```routes
/weibo/super_index/1008084989d223732bf6f02f75ea30efad58a9
```

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [ ] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason

### CODE REVIEW

**Comment by queensferryme** [comment]
我目前的想法是这样的：
1. `utils/date.js` 模块只负责转换时区，将那些正则表达式合并到 `utils/dateParse.js` 模块中去，解耦；
2. `utils/date.js` 提供一个 `date` 函数，接受 string literal 或 String、dayjs、Date 对象；
    - 对于字符串，使用 dayjs 解析再转换为 Date；
    - 对于 dayjs 对象，直接转换为 Date；
    - 最后将 Date 对象的时区转换，并返回 UTC 格式的时间字符串。
3. `utils/date.js` 模块原有的正则最好都用 `^` 和 `$` 给包起来，防止出现部分匹配。

目前只测试了原 issue 中提到的微博超话路由，其他受到影响的路由的测试后续会加进来。

/cc @NeverBehave @DIYgod

**Comment by queensferryme** [comment]
https://github.com/DIYgod/RSSHub/pull/7438#issuecomment-827444530

草，这个自动测试模块看起来有点问题，不是路由的内容也被识别进去了（

**Comment by queensferryme** [comment]
**Progress**:
- [ ] ./test/utils/date.js
- [ ] ./lib/utils/common-config.js
- [ ] ./lib/routes/iyiou/index.js
- [ ] ./lib/routes/saraba1st/thread.js
- [ ] ./lib/routes/medsci/recommend.js
- [ ] ./lib/routes/laosiji/feed.js
- [ ] ./lib/routes/laosiji/hotshow.js
- [ ] ./lib/routes/zhuixinfan/list.js
- [ ] ./lib/routes/qidian/forum.js
- [ ] ./lib/routes/hpoi/info.js
- [ ] ./lib/routes/blogs/diygod/animal-crossing.js
- [ ] ./lib/routes/blogs/wangyin.js
- [ ] ./lib/routes/etoland/board.js
- [ ] ./lib/routes/thepaper/utils.js
- [ ] ./lib/routes/paidai/utils.js
- [ ] ./lib/routes/zaobao/util.js
- [ ] ./lib/routes/meipai/user.js
- [ ] ./lib/routes/yystv/docs.js
- [ ] ./lib/routes/yystv/category.js
- [ ] ./lib/routes/mobdata/report.js
- [ ] ./lib/routes/universities/ncwu/notice.js
- [ ] ./lib/routes/universities/njust/gs/index.js
- [ ] ./lib/routes/universities/njust/eo/index.js
- [ ] ./lib/routes/universities/ahmu/news.js
- [ ] ./lib/routes/universities/nuaa/yjsy/yjsy.js
- [ ] ./lib/routes/universities/whu/cs.js
- [ ] ./lib/routes/universities/bupt/yz.js
- [ ] ./lib/routes/futunn/highlights.js
- [ ] ./lib/routes/cctv/xwlb.js
- [ ] ./lib/routes/reuters/theWire.js
- [ ] ./lib/routes/51voa/channel.js
- [ ] ./lib/routes/ifnews/column.js
- [ ] ./lib/routes/oschina/news.js
- [ ] ./lib/routes/oschina/topic.js
- [ ] ./lib/routes/anitama/channel.js
- [ ] ./lib/routes/scboy/thread.js
- [ ] ./lib/routes/huxiu/utils.js
- [ ] ./lib/routes/javlibrary/utils.js
- [ ] ./lib/routes/21caijing/channel.js
- [ ] ./lib/routes/coronavirus/caixin.js
- [ ] ./lib/routes/guancha/index.js
- [ ] ./lib/routes/guancha/topic.js
- [ ] ./lib/routes/baijing/index.js
- [ ] ./lib/routes/latepost/index.js
- [ ] ./lib/routes/lwn/alerts.js
- [ ] ./lib/routes/chiculture/topic.js
- [ ] ./lib/routes/psnine/game.js
- [ ] ./lib/routes/psnine/shuzhe.js
- [ ] ./lib/routes/psnine/trade.js
- [ ] ./lib/routes/psnine/index.js
- [ ] ./lib/routes/uisdc/topic.js
- [ ] ./lib/routes/tianyancha/hot.js
- [ ] ./lib/routes/bjx/huanbao.js
- [ ] ./lib/routes/weibo/user.js
- [ ] ./lib/routes/weibo/super_index.js
- [ ] ./lib/routes/weibo/keyword.js
- [ ] ./lib/routes/who/news-room.js
- [ ] ./lib/routes/zaker/source.js
- [ ] ./lib/routes/zaker/focusread.js
- [ ] ./lib/routes/d2/daily.js
- [ ] ./lib/routes/totalcommander/whatsnew.js
- [ ] ./lib/routes/magireco/event_banner.js
- [ ] ./lib/routes/magireco/announcements.js
- [ ] ./lib/routes/tencent/wechat/csm.js
- [ ] ./lib/routes/tencent/wechat/wxnmh.js
- [ ] ./lib/routes/tencent/wechat/wemp.js
- [ ] ./lib/routes/tencent/news/author.js
- [ ] ./lib/routes/xyplorer/whatsnew.js
- [ ] ./lib/routes/iresearch/report.js
- [ ] ./lib/routes/yicai/brief.js
- [ ] ./lib/routes/citavi/index.js
- [ ] ./lib/routes/bjnews/news.js
- [ ] ./lib/routes/pubmed/trending.js
- [ ] ./lib/routes/newsmth/section.js
- [ ] ./lib/routes/newsmth/account.js
- [ ] ./lib/routes/dianping/user.js
- [ ] ./lib/routes/aisixiang/utils.js
- [ ] ./lib/routes/checkee/index.js
- [ ] ./lib/routes/dedao/knowledge.js
- [ ] ./lib/routes/p-articles/utils.js
- [ ] ./lib/routes/discuz/discuz.js
- [ ] ./lib/routes/smzdm/haowen_fenlei.js
- [ ] ./lib/routes/smzdm/baoliao.js
- [ ] ./lib/routes/smzdm/haowen.js
- [ ] ./lib/routes/smzdm/article.js
- [ ] ./lib/routes/smzdm/keyword.js
- [ ] ./lib/routes/smzdm/ranking.js
- [ ] ./lib/routes/segmentfault/channel.js
- [ ] ./lib/routes/segmentfault/user.js
- [ ] ./lib/routes/nowcoder/discuss.js
- [ ] ./lib/routes/sohu/mp.js
- [ ] ./lib/routes/gov/moa/moa.js
- [ ] ./lib/routes/gov/nppa/contents.js
- [ ] ./lib/routes/gov/nppa/channels.js
- [ ] ./lib/routes/gov/sapprft/7026.js
- [ ] ./lib/routes/netease/news/special.js
- [ ] ./lib/routes/netease/dy.js
- [ ] ./lib/routes/netease/ds.js
- [ ] ./lib/routes/zhishifenzi/innovation.js
- [ ] ./lib/routes/zhishifenzi/news.js
- [ ] ./lib/routes/zhishifenzi/depth.js

**Comment by NeverBehave** [comment]
现在状况如何

**Comment by SukkaW** [comment]
@NeverBehave 你去跟进这个吧，我去把 route test 那个修掉。。。

**Comment by NeverBehave** [comment]
@queensferryme 

https://github.com/DIYgod/RSSHub/blob/master/lib/utils/dateParser.js

目前这个是没有修订的吗？目前dateParser使用范围是？

@SukkaW ok, 我想在7号左右确定下来然后开始处理现有PR

**Comment by NeverBehave** [comment]
https://github.com/DIYgod/RSSHub/blob/7b473b40f2d75d454fbda6adf3a718502a553ebb/lib/middleware/parameter.js#L37

是不是没有考虑这个进来？

**Comment by NeverBehave** [comment]
确认了一下，所有中间传入都是date object, 缓存时会被自动转换为UTC时间，后续处理会转换回date进行处理
这边似乎并不会造成breaking change， @queensferryme 可以先行合并，后续剩余路由单独开出pr进行修订
文档将会在新的pr处理

**Comment by NeverBehave** [comment]
complimentary branch https://github.com/DIYgod/RSSHub/tree/pubdate
Should merge after this PR

**Comment by queensferryme** [comment]
不好意思，这几天比较忙没怎么看 GitHub。

目前的状况是这样的：原来的 date 模块中许多正则可以使用 dayjs 来代替，叫做 parseDate 模块；时区转换的逻辑在 timezone 模块里处理。

还没完成的部分有：原来的 date 模块中还有一些处理中文相对日期的正则（X天前、X小时前等），这部分我还没做适配，但应该也可以用 dayjs 做到；此外原来的 dateParser 模块我也还没看。

目前我的建议是先合并这个补丁，然后鼓励后续 pr 优先使用新的 timezone / parseDate 模块。旧的 date / dateParser 模块为兼容性暂时保留，直到所有受影响路由处理完毕后再移除。

**Pull request merged**
