### PR TITLE
ci: ignore route test on forks

### PR DESCRIPTION
**Pull request by liyishuai**
## 完整路由地址 / Example for the proposed route(s)
```routes
noroute
```
## 说明 / Note
Automated pull requests to forks like liyishuai/RSSHub#1007 are closed because `routes` was unspecified. No need to check this on forks.

### CODE REVIEW

**Review by SukkaW — CHANGES_REQUESTED** [review]
What happened if we decide to change our repo to a specific org like `RSSHub`? Depending on repo owner is a bit footgun. A better approach should be based on environment variable.

**Comment by liyishuai** [comment]
Yes that makes sense. What non-private variable has this repo specified?

**Comment by Rongronggg9** [comment]
what about `if: github.actor != github.repository_owner`?

**Comment by liyishuai** [comment]
Nice catch. Thanks!

**Comment by TonyRL** [comment]
FYI, you can disable unwanted workflow(s) in the tabs

**Comment by liyishuai** [comment]
For future reference: The button is hidden under "..." menu. GitHub seems to have a different mindset from its users.
image

**Pull request closed without merging**
