### PR TITLE
fix(route/zhihu): Fix `d_c0`

### PR DESCRIPTION
**Pull request by dzx-dzx**
## Involved Issue / 该 PR 相关 Issue

Close #

## Example for the Proposed Route(s) / 路由地址示例

```routes
/zhihu/people/activities/diygod
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

### CODE REVIEW

**Comment by fenhaizi** [comment]
after this fix, no more error messages, but the output become truncated again, regardless of whether "ZHIHU_COOKIES" environment is present or not

**Comment by dzx-dzx** [comment]
@fenhaizi Did you provide the `d_c0` cookie? And what's the exact route?

**Comment by fenhaizi** [comment]
> @fenhaizi Did you provide the `d_c0` cookie(I'm not saying that you must)? And what's the exact route?

You may have said in other posts that `d_c0` is obtained from requests but not explicitly provided by user, so, I have not provided `d_c0`

btw, how to provide 2+ cookies (`z_c0` and `d_c0` in this case) in one ZHIHU_COOKIE parameter?

**Comment by fenhaizi** [comment]
> @fenhaizi Did you provide the `d_c0` cookie(I'm not saying that you must)? And what's the exact route?

You may have said in other posts that `d_c0` is obtained from requests but not explicitly provided by user, so, I have not provided `d_c0`

btw, how to provide 2+ cookies (`z_c0` and `d_c0` in this case) in one ZHIHU_COOKIE parameter?

**Comment by dzx-dzx** [comment]
It is this very PR that I added the feature to import `d_c0` from the config, but the original method is kept as a backup plan if the cookie is not provided, and as I've just tested, works.

So what route are you accessing?

**Comment by fenhaizi** [comment]
> It is this very PR that I added the feature to import `d_c0` from the config, but the original method is kept as a backup plan if the cookie is not provided, and as I've just tested, works.
> 
> So what route are you accessing?

an example route is zhihu/people/activities/12cc8f31c86df523717b159f5075b9d3

**Comment by dzx-dzx** [comment]
> btw, how to provide 2+ cookies (z_c0 and d_c0 in this case) in one ZHIHU_COOKIE parameter?

Separated by ';', as per its standard format.

**Comment by dzx-dzx** [comment]
> after this fix, no more error messages, but the output become truncated again, regardless of whether "ZHIHU_COOKIES" (regarding to z_c0) in environment is present or not

I'm not able to reproduce that.

**Comment by dzx-dzx** [comment]
> after this fix, no more error messages, but the output become truncated again

You found your output being truncated right after this pr, with no configuration changed? And it had been normal before it?

**Comment by fenhaizi** [comment]
> > after this fix, no more error messages, but the output become truncated again
> 
> You found your output being truncated right after this pr, with no configuration changed? And it had been normal before it?

I have clean-redeployed the whole RSSHub many times, and clean all related containers/images/volumes (including but not limited to: rsshub, redis, browserless) before each re-deploy. At least 4 times (corresponding to the 4 cases mentioned above), still get incomplete answers. the two cookies values are get newly, and "forgot" all previously used values.

btw, are you deploying with docker-compose or otherwise? if docker-compose, are you using docker.com source or ghcr.io source?

**Comment by dzx-dzx** [comment]
I use my local development environment. The code is the same as the master branch.

Did you pull a new version of Docker image last night, and found that your previously working instance stopped serving the full content? Have you ever observed a normal result, since https://github.com/DIYgod/RSSHub/pull/16281 is being merged?

**Comment by fenhaizi** [comment]
I pulled and deployed the image many times in these two days, and now it works without truncating. but still not knowing the reasons behind

I dare not rebooting the server, because last days rsshub for zhihu often stop working after reboots, and it is lengthy process to get it back working, without knowing the reason.

I have set ZHIHU_COOKIES `z_c0` only without `d_c0` or others,but ZHIHU_COOKIES being 'z_c0`:`xxxxxxxxxxxxxxx' worked but not works now, and 'z_c0`=`xxxxxxxxxxxxxxx' works

**Comment by fenhaizi** [comment]
sorry for my not familiar with http(s) protocol, especially cookies

**Pull request merged**
