### PR TITLE
fix: remove pornhub preview video

### PR DESCRIPTION
**Pull request by I2IMk**
## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

/pornhub/category_url/
/pornhub/category_url/popularwithwomen

### CODE REVIEW

**Comment by HenryQW** [comment]
Any reason why?

**Comment by I2IMk** [comment]
@HenryQW 
These preview videos extracted will expire in (exactly) two hours, which is too short for feed. 
Some video urls have indicated this: `https://ew.phncdn.com/videos/../360P_360K_.._fb.mp4?validfrom=1598770991&validto=1598778191&rate=150k&burst=1000k&hash=..`

**Comment by HenryQW** [comment]
Is it possible to obtain a permanent src?

**Comment by I2IMk** [comment]
I don't think so. Since these preview links look so similar to streaming ones, the restrictions imposed should be similar too. 

The [webmaster API](https://github.com/pionxzh/Pornhub.js/blob/master/src/webmaster/index.js) won't give a preview video as well, e.g. `https://www.pornhub.com/webmasters/video_by_id?id=ph5ecf18b141646&thumbsize=large_hd`

I have replaced preview videos to static thumbnails.

**Pull request merged**
