### PR TITLE
Fix acwifi.net support

### PR DESCRIPTION
**Pull request by tylinux**
## 完整路由地址 / Example for the proposed route(s)

```routes
/acwifi/
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [ ] New Route
- [ ] Documentation
  - [ ] CN
  - [ ] EN
- [x] 全文获取 fulltext
  - [x] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] 日期和时间 date and time
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [x] `Puppeteer`

### CODE REVIEW

**Comment by TonyRL** [comment]
Did you try `https://www.acwifi.net/feed` before switching to puppeteer approach?

**Comment by tylinux** [comment]
> Did you try `https://www.acwifi.net/feed` before switching to puppeteer approach?

Yes, I can comfirm it's worked.

**Comment by TonyRL** [comment]
> > Did you try `https://www.acwifi.net/feed` before switching to puppeteer approach?
> 
> Yes, I can comfirm it's worked.

If `https://www.acwifi.net/feed` works then, you should use that instead of puppeteer approach

**Comment by tylinux** [comment]
acwifi.net use baidu CDN to protect his resources, so this fix is unstable, close it.

**Pull request closed without merging**
