### PR TITLE
fix(route): CDRHNew, add new route with only title

### PR DESCRIPTION
**Pull request by christaikobo**
## 该 PR 相关 Issue / Involved issue
No related issue
Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/fda/cdrh
/fda/cdrh-title
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [ ] 新的路由 New Route
  - [x] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [x] 文档说明 Documentation
  - [x] 中文文档 CN
  - [x] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [x] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

## 说明 / Note
Added new subroute: cdrh-title
/fda/cdrh would generate a lot of entries with different titles but similar contents, which would be filtered by de-duplicate algorithm.
For some RSS reader with heavy de-duplicate algorithm, /fda/cdrh-title would preserve all entries.

### CODE REVIEW

**Review by TonyRL — COMMENTED** [review]
You can add an optional parameter to the existing route to achieve the same thing

```diff
module.exports = async (ctx) => {
+   const titleOnly = !!(ctx.params.titleOnly ?? '');
    const rootUrl = 'https://www.fda.gov';
    const currentUrl = `${rootUrl}/medical-devices/news-events-medical-devices/cdrhnew-news-and-updates`;
```

```diff
                try {
                    item.pubDate = parseDate(content('meta[property="article:published_time"]').attr('content').split(', ').pop(), 'MM/DD/YYYY - HH:mm');
                } catch (e) {
                    item.pubDate = parseDate(content('meta[property="article:published_time"]').attr('content'));
                }

-                item.description = content('div[role="main"], .doc-content-area').html();
+                item.description = titleOnly ? null : content('div[role="main"], .doc-content-area').html();
+                item.guid = titleOnly ? `${item.link}#titleOnly` : item.link;

                return item;
```

**Comment by terrytw** [comment]
> 

Can you please explain how it works? I don't know js too well.

**Comment by TonyRL** [comment]
v2/fda/router.js
```diff
module.exports = function (router) {
-    router.get('/cdrh', require('./cdrh'));
+    router.get('/cdrh/:titleOnly?', require('./cdrh'));
};
```

**Comment by terrytw** [comment]
OK, thanks, I think I will open another PR.

**Pull request closed without merging**
