### PR TITLE
fix(route/twitter): Prevent storing empty cookie if obtaining such from `auth_token` failed.

### PR DESCRIPTION
**Pull request by dzx-dzx**
## Involved Issue / 该 PR 相关 Issue

Close #

## Example for the Proposed Route(s) / 路由地址示例

```routes
/twitter/user/DIYgod
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

### CODE REVIEW

**Comment by AiraNadih** [comment]
This commit broke the RSSHub instances that authenticate using `auth_token`.

I suspect the issue might be here:

https://github.com/DIYgod/RSSHub/blob/c8496f370b0ddde572420620332511d0b848e726/lib/routes/twitter/api/web-api/utils.ts#L43

**Comment by dzx-dzx** [comment]
@AiraNadih  It works on my side. What error messages are given?

**Comment by AiraNadih** [comment]
> @AiraNadih It works on my side. What error messages are given?

```
Error in /twitter/home/onlyMedia=1: ConfigNotFoundError: Twitter cookie for token *** is not valid
```

**Comment by dzx-dzx** [comment]
I don't think the token method is stable, even before this pr. Please try a few times more.

**Comment by AiraNadih** [comment]
> I don't think the token method is stable, even before this pr. Please try a few times more.

But after I rolled back to commit 682c943, it was normal.

**Comment by AiraNadih** [comment]
I just tested it again.
Including the two times I tested it when I commented before, that's a total of three times now.

The first request after initial deployment is normal, but subsequent requests will result in errors.

Rolling back to the previous commit works correctly.
Therefore, I am certain that some part of this commit must have broken the relevant logic.

**Comment by flameleaf** [comment]
One strange quirk I've noticed about the auth_token cookie is that quoting the variable sometimes fixes it. It'll randomly fail on my deployment, but if I change it from TWITTER_AUTH_TOKEN=token_name to TWITTER_AUTH_TOKEN='token_name', or vice-versa, it'll return to a usable state.

**Comment by AiraNadih** [comment]
Seeing the latest merged PR #17429, I finally understand where the problem lies.

**Pull request merged**
