### PR TITLE
Add(route): add 北京市科委

### LINKED ISSUE #8809: 北京市科委通知公告RSS订阅
### 类型

政务消息

### 网站地址

http://kw.beijing.gov.cn/col/col736/index.html

### 网站描述

北京市科委通知公告

### 需要生成什么内容？

通知公告的标题及相应链接

### 额外描述

_No response_

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

### PR DESCRIPTION
**Pull request by Fatpandac**
## 该 PR 相关 Issue / Involved issue

Close #8809

## 完整路由地址 / Example for the proposed route(s)

```routes
/gov/beijing/kw/col736
/gov/beijing/kw/col1132
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [X] New Route
- [X] Documentation
  - [X] CN
  - [ ] EN
- [X] 全文获取 fulltext
  - [X] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [X] 日期和时间 date and time
  - [X] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

### CODE REVIEW

**Comment by TonyRL** [comment]
Will you consider switching to  `/gov/beijing/kw/:channel`? 
There are a lot of gov-related routes in this format already.

https://github.com/DIYgod/RSSHub/blob/b8acfdbf7bc371f2c91ff33c0ea85f1db8b43410/lib/router.js#L1348-L1361

**Comment by Fatpandac** [comment]
> Will you consider switching to `/gov/beijing/kw/:channel`? There are a lot of gov-related routes in this format already.
> 
> https://github.com/DIYgod/RSSHub/blob/b8acfdbf7bc371f2c91ff33c0ea85f1db8b43410/lib/router.js#L1348-L1361

How can I name the folder?
Folder named gov then the router.js write `/beijing/kw/:channel`?

**Comment by fredericky123** [comment]
这个是不是还没做好？
怎么点击链接无法生成rss呢

**Comment by Fatpandac** [comment]
> 这个是不是还没做好？
> 
> 怎么点击链接无法生成rss呢

可以了，只不过还没有合并
[测试部署的 rss 地址](https://rsshub-4euejr03d-diy.vercel.app/gov/beijing/kw/col736)，可以考虑先用这个，如果急需

**Comment by fredericky123** [comment]
谢谢！原来是我点错链接了（https://rsshub-git-fork-fatpandac-feature-kwbeijing-diy.vercel.app）

**Comment by TonyRL** [comment]
FYI, preview links from Vercel is used for CI only. Certain limitations were added to prevent it being used in common RSS clients in order to prevent repo owner's account from exceeding Free plan limits.

**Comment by fredericky123** [comment]
> FYI, preview links from Vercel is used for CI only. Certain limitations were added to prevent it being used in common RSS clients in order to prevent repo owner's account from exceeding Free plan limits.

Thanks for this information!

**Comment by fredericky123** [comment]
https://rsshub.app/gov/beijing/kw/col736
这个网址好像被阻拦了，怎么办呢

**Comment by Fatpandac** [comment]
@fredericky123 
已提交 PR 处理

**Comment by fredericky123** [comment]
> @fredericky123 已提交 PR 处理

非常感谢！

**Pull request merged**
