### PR TITLE
fix(route): xiaohongshu fulltext add cookie authentication

### LINKED ISSUE #16300: 小红书文章列表加载不出来
### Routes

```routes
/xiaohongshu/user/:user_id/notes/fulltext
```

### Full routes

```fullroutes
/xiaohongshu/user/6477f4590000000012034f1f/notes/fulltext
```

### Related documentation

https://docs.rsshub.app/zh/routes/social-media#unknown-3

### What is expected?

能正常加载处理

### What is actually happening?

image
image

### Deployment information

RSSHub demo (https://rsshub.app)

### Deployment information (for self-hosted)

_No response_

### Additional info

```shell
Bad gateway Error code 502
Visit cloudflare.com for more information.
2024-07-30 03:01:57 UTC
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

### PR DESCRIPTION
**Pull request by dddaniel1**
## Involved Issue / 该 PR 相关 Issue

Close #16300

## Example for the Proposed Route(s) / 路由地址示例

```routes
/xiaohongshu/user/52d8c541b4c4d60e6c867480/notes
/xiaohongshu/user/52d8c541b4c4d60e6c867480/notes/fulltext
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

## Note / 说明
代码借鉴[rien7](https://github.com/rien7)这位大佬

### CODE REVIEW

**Comment by dddaniel1** [comment]
> Successfully [generated](https://github.com/DIYgod/RSSHub/actions/runs/11460576994) as following:
> 
> http://localhost:1200/xiaohongshu/user/52d8c541b4c4d60e6c867480/notes - Success ✔️
> http://localhost:1200/xiaohongshu/user/52d8c541b4c4d60e6c867480/notes/fulltext - Failed ❌
失败的路由需要cookie,才能使用

**Comment by hujh818** [comment]
请问什么时候能合并呢？

**Comment by wwyf** [comment]
I deployed and tested the PR's code, and it works. I hope someone can review and merge this PR.

我自己部署并测试了一下该 pr 的代码，确实是能用的，可以爬取小红书正文，如果能 merge 主线的话会更方便一些

**Comment by dddaniel1** [comment]
> I deployed and tested the PR's code, and it works. I hope someone can review and merge this PR.
> 
> 我自己部署并测试了一下该 pr 的代码，确实是能用的，可以爬取小红书正文，如果能 merge 主线的话会更方便一些

merge主线是啥意思，第一次提pr

**Pull request merged**
