### PR TITLE
a little patch. github feed tips

### PR DESCRIPTION
**Pull request by sgqy**

### CODE REVIEW

**Comment by HenryQW** [comment]
顺便加上英文版的吧

Private feed: https://github.com/:user.private.atom?token=:secret (Visit [GitHub Dashboard](https://github.com/), scroll to the bottom and find **Subscribe to your news feed**)

**Comment by DIYgod** [comment]
Merged, thanks!

**Comment by sgqy** [comment]
还有个patch刚push上来，就差了1秒………………

**Comment by sgqy** [comment]
```markdown
-   Private feed: https://github.com/:user.private.atom?token=:secret (You can find **Subscribe to your news feed** in [dashboard](https://github.com) page after login)
```
```markdown
-   专属动态: https://github.com/:user.private.atom?token=:secret (登录后在[仪表盘页面](https://github.com)找到 **Subscribe to your news feed** 字样即可)
```
~~找个别的地儿加进去也行~~

**Comment by DIYgod** [comment]
@squkw 手动合进来啦 8bc7fcd9a05f92bd69ee24a527183af29d4ded22

**Pull request merged**
