### PR TITLE
feat: support twreporter

### LINKED ISSUE #4838: 希望添加报导者 The Reporter

### PR DESCRIPTION
**Pull request by emdoe**
## 该 PR 相关 Issue / Involved issue

(Reopen and) close #4838.

@jessejesset

## 完整路由地址 / Example for the proposed route(s)

- `/twreporter/newest`
- `/twreporter/photography`
- `/twreporter/category/reviews`

另外，需要注意的是：

1. 偶有极个别文章不能全文输出（即未能完整加载一些图片）
2. 当前不支持网站的 categories/infographics

### CODE REVIEW

**Comment by oppilate** [comment]
> *   偶有极个别文章不能全文输出（即未能完整加载一些图片）

Can you take an example?

> 当前不支持网站的 categories/infographics

Maybe use `$('[class^="metadata__TagButton-"]')` to extract tags? Actually everything is at `https://go-api.twreporter.org/v2/posts/criminal-custodial-protection-prolonging-dabate?full=true`. You can make a PR to https://github.com/twreporter/twreporter-react/blob/2efefbdd063e9774f8709463015cb99a0f97649c/src/html.js to add categories directly to the vanilla RSS feed if you like.

**Comment by emdoe** [comment]
> Can you take an example?

see https://www.twreporter.org/a/photo-the-silence-to-you-one-story-at-a-time


> Maybe use `$('[class^="metadata__TagButton-"]')` to extract tags? Actually everything is at `https://go-api.twreporter.org/v2/posts/criminal-custodial-protection-prolonging-dabate?full=true`. You can make a PR to https://github.com/twreporter/twreporter-react/blob/2efefbdd063e9774f8709463015cb99a0f97649c/src/html.js to add categories directly to the vanilla RSS feed if you like.

Wow, thanks! I will check it later (when I'm available)

**Comment by oppilate** [comment]
For \```https://go-api.twreporter.org/v2/posts/covid-2019-keep-tracking-gcs?full=true` `` I'd suggest inserting hero to the top of `content` section (which is undefined in this case).

For `https://go-api.twreporter.org/v2/posts/photo-the-silence-to-you-one-story-at-a-time?full=true`, maybe extract images from the HTML (meaning assambled code from json), and insert those accordingly.

**But** since you are interested in directly improving twreporter's codebase, the above will be useless. I'd prefer to directly commit to their repo, too, because it'll benifit more people and enable more usages. Fetching HTML is probably feasible because there was  twreporter/go-api@217c410.

**Comment by emdoe** [comment]
> I'd prefer to directly commit to their repo, too, because it'll benifit more people and enable more usages.

Sure! I really appreciate their ideas, works, & open approach, and definitely it's appealing to me to do something the broader audience can benefit from. However, I may need a little time to get familiar with their code base because at this time I can't estimate whether this is a long-winded road and how & what I can improve the reading experience for their readers.

> Fetching HTML is probably feasible because there was  twreporter/go-api@217c410.

I will check it. Thanks!

> BTW, please tell me if there is anything I can help. I'd love to contribute to twreporter.

Thanks! I think I need some extra time to think clearer, and then I may have a better plan.

**Pull request merged**
