### PR TITLE
fix(route): 修正知网作者最新发布的期刊文献

### LINKED ISSUE #12490: 知网作者期刊文献疑似无法使用
### 路由地址

```routes
/cnki/author/:code
```

### 完整路由地址

```fullroutes
/cnki/author/000037748936
```

### 相关文档

https://docs.rsshub.app/journal.html#zhong-guo-zhi-wang

### 预期是什么？

可以在inoreader订阅。

### 实际发生了什么？

除了rsshub给定举例外，在inoreader里面无法订阅。

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by Derekmini**
## 该 PR 相关 Issue / Involved Issue

Close #12490

## 路由地址示例 / Example for the Proposed Route(s)

```routes
/cnki/author/000042423923
/cnki/author/000040489945
```

## 新 RSS 路由检查表 / New RSS Route Checklist
  
- [ ] 新的路由 New Route
  - [ ] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [ ] 文档说明 Documentation
  - [ ] 中文文档 CN
  - [ ] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

### CODE REVIEW

**Comment by Derekmini** [comment]
> Successfully [generated](https://github.com/DIYgod/RSSHub/actions/runs/4844345267) as following:
> 
> http://localhost:1200/cnki/author/000042423923 - Failed ❌
> http://localhost:1200/cnki/author/000040489945 - Failed ❌

是不是被知网屏蔽了？我刚本地测试了一遍还是可以获取到条目的。

**Comment by Derekmini** [comment]
@harveyqiu 

我刚刚发现了一个小问题：

RSS客户端是以link作为item的唯一标识的，但是，由于每次都获取了新的code2，就导致每次获取的link也不一样，最终在RSS客户端里总是获得了新的链接，最终导致每次获取都是旧的内容。

我初步想，可以把题目作为唯一识别，放到link中，而真实的link放到正文内。

**Comment by Derekmini** [comment]
> Successfully [generated](https://github.com/DIYgod/RSSHub/actions/runs/4847938002) as following:
> 
> http://localhost:1200/cnki/author/000042423923 - Failed ❌
> http://localhost:1200/cnki/author/000040489945 - Failed ❌

是不是被知网屏蔽了？我刚本地测试了一遍还是可以获取到条目的。

**Comment by harveyqiu** [comment]
> > Successfully [generated](https://github.com/DIYgod/RSSHub/actions/runs/4847938002) as following:
> > http://localhost:1200/cnki/author/000042423923 - Failed ❌
> > http://localhost:1200/cnki/author/000040489945 - Failed ❌
> 
> 是不是被知网屏蔽了？我刚本地测试了一遍还是可以获取到条目的。

- https://www.timeshighereducation.com/news/china-block-foreign-access-journal-portal-damages-knowledge
- https://www.voanews.com/a/china-to-limit-access-to-largest-academic-database-/7029581.html

**Review by TonyRL — COMMENTED** [review]
Maybe add a warning telling users that this RSS feed is IP locked to mainland China only.

<details><summary>Screenshot</summary>

image
</details>

**Pull request merged**
