### PR TITLE
feat(config): support URL prefix

### PR DESCRIPTION
**Pull request by heimoshuiyu**
## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [ ] 新的路由 New Route
  - [ ] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [x] 文档说明 Documentation
  - [x] 中文文档 CN
  - [x] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

## 说明 / Note

添加了对 URL 路径前缀的支持，通过环境变量 `PREFIX` 设置。默认值为空字符串。

例如设置 `PREFIX=/prefix` 将需要使用 <https://rsshub.app/prefix/qdaily/column/59> 进行访问。

这个功能使得 RSSHub 可以部署（藏）在某些网站 URL 后面。

### CODE REVIEW

**Comment by heimoshuiyu** [comment]
忽然发现 v2 的 routes 没改，force push 了一遍（

**Comment by TonyRL** [comment]
Can you name it `pathPrefix`?
There's a `suffix` that appends extra wording to feed items. Having `prefix` and `suffix` with completely different usage seems a bit misleading.

**Comment by heimoshuiyu** [comment]
It looks like there is a conflict, do I need to rebase my branch?

**Review by SukkaW — CHANGES_REQUESTED** [review]
RSSHub can be deployed to any sub-directories, so there is no need for a dedicated configuration.

**Comment by heimoshuiyu** [comment]
> RSSHub can be deployed to any sub-directories, so there is no need for a dedicated configuration.

Could you please explain how to do it?

**Pull request closed without merging**
