### PR TITLE
Catch up US Reuters's redesigned page:

### PR DESCRIPTION
**Pull request by LyleLee**
which is announced at 15 April 2021, 2:00 pm.
https://www.reutersagency.com/en/media-center/welcome-to-the-new-reuters-com/

Update the following  #routes:

/reuters/channel/us/business
/reuters/channel/us/markets
/reuters/channel/us/world
/reuters/channel/us/politics
/reuters/channel/us/technology
/reuters/channel/us/breakingviews
/reuters/channel/us/lifestyle

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/reuters/channel/us/business
/reuters/channel/us/markets
/reuters/channel/us/world
/reuters/channel/us/politics
/reuters/channel/us/technology
/reuters/channel/us/breakingviews
/reuters/channel/us/lifestyle
```

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [ ] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason

### CODE REVIEW

**Comment by LyleLee** [comment]
@HenryQW Would you mind speeding up this PR a little bit. I am looking forward to have it merged to fix my broken rss feed. Thanks a lot.

**Review by NeverBehave — CHANGES_REQUESTED** [review]
Test Route issue: is it blocked or expected behavior?

**Comment by LyleLee** [comment]
`/reuters/channel/us/markets` is not expected.
`/reuters/channel/us/politics ` is failed, because Reuters.com have no such route.

**Comment by oppilate** [comment]
@LyleLee Can you adjust the categories according to the new ones?

- World
- Business
- Legal
- MarketsBreakingviews
- Technology
- InvestigationsLifestyle

Also, looks like they merged the us and uk sites into a "world" site. So only keep one of them or keep both of them for compatibility but return the same results?

**Comment by LyleLee** [comment]
> @LyleLee Can you adjust the categories according to the new ones?
> 
> * World
> * Business
> * Legal
> * MarketsBreakingviews
> * Technology
> * InvestigationsLifestyle
> 
> Also, looks like they merged the us and uk sites into a "world" site. So only keep one of them or keep both of them for compatibility but return the same results?

OK, I think I can spare some a little time to do it this week. Hold on a while.

**Comment by LyleLee** [comment]
It turn out that there is quite extra work to do, i can't keep all categories alive right now.  
```
us	World		https://www.reuters.com/world √
us	Business	https://www.reuters.com/business √
us	Legal		https://www.reuters.com/legal ×
us	Markets		https://www.reuters.com/markets ×
us	Breakingviews	https://www.reuters.com/breakingviews √
us	Technology	https://www.reuters.com/technology √
us	investigates	https://www.reuters.com/investigates ×
us	lifestyle	https://www.reuters.com/lifestyle √
```

**Comment by LyleLee** [comment]
I have managed to fix it. New PR is here: https://github.com/DIYgod/RSSHub/pull/7825

**Comment by SettingDust** [comment]
Should this close?

**Comment by LyleLee** [comment]
> Should be closed?

Yes, time to move forward.  :)

**Pull request closed without merging**
