### PR TITLE
添加对 【IPSW.ME】的支持

### PR DESCRIPTION
**Pull request by Jeason0228**
#3159 @MisterGlasses 

支持关注系列类固件如:
http://rsshub.app/ipsw/index/ipsws/iPhone
http://rsshub.app/ipsw/index/ipsws/iPad
支持关注指定机型固件如:
http://rsshub.app/ipsw/index/ipsws/iPone11,8

### CODE REVIEW

**Comment by MisterGlasses** [comment]
谢谢


________________________________
发件人: Jeason0228 <notifications@github.com>
发送时间: 星期四, 十月 3, 2019 00:48
收件人: DIYgod/RSSHub
抄送: Mr.Glasses; Mention
主题: [DIYgod/RSSHub] 添加对 【IPSW.ME】的支持 (#3186)


#3159<https://github.com/DIYgod/RSSHub/issues/3159> @MisterGlasses<https://github.com/MisterGlasses>

支持关注系列类固件如:
http://rsshub.app/ipsw/index/ipsws/iPhone
http://rsshub.app/ipsw/index/ipsws/iPad
支持关注指定机型固件如:
http://rsshub.app/ipsw/index/ipsws/iPone11,8

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/DIYgod/RSSHub/pull/3186

Commit Summary

  *   添加对sketch.com 的beta版本更新支持
  *   npm fortmat产生的什么鬼
  *   为Xml增加css样式
  *   增加对Sketch 正式版的RSS 支持
  *   文档增加sketch 更新的描述
  *   更新sketch RSS内容
  *   修正sketch提交Rss代码格式
  *   Update package.json
  *   多余的修改...总是被提交
  *   Create package.json
  *   回滚多余修改
  *   Update atom.art
  *   Merge branch 'master' of https://github.com/Jeason0228/RSSHub
  *   Merge branch 'master' into master
  *   优化sketch beta对已发布的情况输出item信息. 优化update是的输出信息
  *   Merge branch 'master' into master
  *   PS4 系统更新纪录 RSS
  *   Merge branch 'master' of https://github.com/Jeason0228/RSSHub
  *   Update ps4updates.js
  *   添加对 鲸跃汽车文章 的支持
  *   加refer
  *   Revert "加refer"
  *   加Refer
  *   修复 鲸跃汽车 其他栏目的举例URL
  *   Merge pull request #1 from DIYgod/master
  *   【深圳证券交易所-上市公告-可转换债券】
  *   Merge pull request #2 from Jeason0228/szse
  *   添加对 【IPSW.ME】的支持

File Changes

  *   M docs/other.md<https://github.com/DIYgod/RSSHub/pull/3186/files#diff-0> (6)
  *   M docs/program-update.md<https://github.com/DIYgod/RSSHub/pull/3186/files#diff-1> (6)
  *   M lib/router.js<https://github.com/DIYgod/RSSHub/pull/3186/files#diff-2> (6)
  *   A lib/routes/ipsw/index.js<https://github.com/DIYgod/RSSHub/pull/3186/files#diff-3> (136)
  *   A lib/routes/szse/notice.js<https://github.com/DIYgod/RSSHub/pull/3186/files#diff-4> (86)

Patch Links:

  *   https://github.com/DIYgod/RSSHub/pull/3186.patch
  *   https://github.com/DIYgod/RSSHub/pull/3186.diff

―

**Comment by Jeason0228** [comment]
11:41:18 AM: [ERROR] Deploy logs are currently unavailable. We are working on resolving the issue.

???

**Comment by MisterGlasses** [comment]
Looks like something went wrong

**Comment by MisterGlasses** [comment]
050A5FEC-2805-497A-89FF-F0B3DE34E874
链接打开错误

**Pull request closed without merging**
