### PR TITLE
fix: date parsing bug in jwc.ts

### PR DESCRIPTION
**Pull request by ywh555hhh**
## Involved Issue / 该 PR 相关 Issue

Close #

## Example for the Proposed Route(s) / 路由地址示例

```routes
ncu/jwc
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

## Note / 说明

date parsing bug in jwc.ts

### CODE REVIEW

**Review by TonyRL — COMMENTED** [review]
How come we know if the bug is fixed when you decided to skip auto route testing

**Review by TonyRL — COMMENTED** [review]
I don't think having items from the future is considered as fixed.

**Comment by ywh555hhh** [comment]
Thank you for your feedback. I'm eager to address any concerns. Could you please clarify the 'items from the future' issue so I can try to resolve it?"

**Comment by TonyRL** [comment]
Please take a look at the result of auto route testing.

**Pull request closed without merging**
