### PR TITLE
feat(route): add 反向代理 (#7122)

### LINKED ISSUE #7122: 【功能需求】反代理rss订阅地址
### 这是一个什么样的功能？
反代理rss订阅地址
### 这个功能可以解决什么问题？
使用ttrss订阅一些rss会出现问题，有的rss订阅地址，用其它rss订阅器是正常没有问题的，可以获取内容，但是用ttrss订阅就是无法获取内容，其中有个问题是ttrss的ssl要求严格，有的订阅地址ssl证书可能有些问题，无法订阅，所以我希望可以通过rsshub解决！
### 额外描述
希望rsshub有个反代理的功能，比如这个订阅源 https://article.pchome.net/rss/147.xml ，ttrss就无法订阅，如果可以使用，如rsshub.app/feed/https://article.pchome.net/rss/147.xml 这样反代理订阅就没有问题就可以了。

image

### PR DESCRIPTION
**Pull request by ccat3z**
## 该 PR 相关 Issue / Involved issue

Close https://github.com/DIYgod/RSSHub/issues/7122

## 完整路由地址 / Example for the proposed route(s)

```routes
/reverse-proxy/https%3A%2F%2Frsshub.app%2Frsshub%2Froutes 
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [x] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason

### CODE REVIEW

**Review by SukkaW — CHANGES_REQUESTED** [review]
Rejected due to security reasons.

**Comment by tuzi3040** [comment]
This don't have to be rejected.
This route can be added to `protected_route.js`, and add something to enroll `HTTP_BASIC_AUTH_NAME` and `HTTP_BASIC_AUTH_PASS` whenever rsshub is started while `NODE_ENV` set to `production`.

**Review by Colin-XKL — CHANGES_REQUESTED** [review]
Verify target url to prevent from abusing. Only accept xml and atom requests

**Comment by NeverBehave** [comment]
https://github.com/DIYgod/RSSHub/discussions/6671

There is actually discussion about this, and we would like to make a RSSHub more generic if possible. There is a long way to go tbh, and right now what (I am) doing is to de-couple scripts/middleware and leave more rooms for this kind of changes. But right now, I would rather keep this as a standalone function (not integrated into RSSHub)

Related https://github.com/DIYgod/RSSHub/issues/6691

**Comment by ruleroller** [comment]
@ccat3z 似乎无法支持一些不太规则的rss地址，例如：[此地址](https://www.reddit.com/r/BattlefieldV/top/.rss)
 ，不知是否可以改进一下。


image

**Comment by auto-bot-ty** [comment]
> @ccat3z 似乎无法支持一些不太规则的rss地址，例如：[此地址](https://www.reddit.com/r/BattlefieldV/top/.rss)
> ，不知是否可以改进一下。
> 
> image
`reverse-proxy/https%3A%2F%2Fwww.reddit.com%2Fr%2FBattlefieldV%2Ftop%2F.rss/` 地址后面加 `/`

**Comment by ruleroller** [comment]
> > @ccat3z 似乎无法支持一些不太规则的rss地址，例如：[此地址](https://www.reddit.com/r/BattlefieldV/top/.rss)
> > ，不知是否可以改进一下。
> > image
> > `reverse-proxy/https%3A%2F%2Fwww.reddit.com%2Fr%2FBattlefieldV%2Ftop%2F.rss/` 地址后面加 `/`

谢谢！可行！

**Pull request closed without merging**
