### PR TITLE
fix(parameter): adjust to filter before limit.

### PR DESCRIPTION
**Pull request by honue**
## Involved Issue / 该 PR 相关 Issue

Close #

## Example for the Proposed Route(s) / 路由地址示例

```routes
/test/filter-limit?filterout_title=2&limit=2
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [v2 Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [v2 路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Documentation / 文档说明
  - [ ] EN / 英文文档
  - [ ] CN / 中文文档
- [ ] Full text / 全文获取
  - [ ] Use cache / 使用缓存
- [ ] Anti-bot or rate limit / 反爬/频率限制 
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施? 
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

## Note / 说明
https://github.com/DIYgod/RSSHub/discussions/13674#discussioncomment-7457216

### CODE REVIEW

**Review by TonyRL — COMMENTED** [review]
It would be better to have a test case so https://github.com/DIYgod/RSSHub/discussions/13674#discussioncomment-7457216 won't happen again during refactoring.

You can take a look at https://github.com/DIYgod/RSSHub/blob/master/lib/v2/test/index.js and https://github.com/DIYgod/RSSHub/blob/master/test/middleware/parameter.js

**Comment by honue** [comment]
A test case has been added. The default 6 test items are used, so index.js has not been modified.

**Comment by honue** [comment]
I don't know if the description of the test case is appropriate, should I use "filter before limit" or keep it?

**Comment by TonyRL** [comment]
> use "filter before limit"
Sure.

**Pull request merged**
