### PR TITLE
feat(core): add HTML feed

### PR DESCRIPTION
**Pull request by JimenezLi**
## Involved Issue / 该 PR 相关 Issue

Close #

## Example for the Proposed Route(s) / 路由地址示例

```routes
/baidu/tieba/forum/rss.html
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [v2 Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [v2 路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [x] Documentation / 文档说明
  - [x] EN / 英文文档
  - [x] CN / 中文文档
- [ ] Full text / 全文获取
  - [ ] Use cache / 使用缓存
- [ ] Anti-bot or rate limit / 反爬/频率限制 
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施? 
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

## Note / 说明
I see [RSS-Bridge](https://github.com/RSS-Bridge/rss-bridge) has a HTML feed, so I add one for RSSHub. (The CSS format is copied from RSS-Bridge.) Here is an example:
<details><summary>/baidu/tieba/forum/rss.html</summary></details>

### CODE REVIEW

**Review by TonyRL — COMMENTED** [review]
People are supposed to read the feeds from their choice of RSS reader.

**Comment by DIYgod** [comment]
Can you explain what it is used for or what advantages does it have compared to using an RSS reader directly?

**Comment by JimenezLi** [comment]
> Can you explain what it is used for or what advantages does it have compared to using an RSS reader directly?

Maybe as a RSS preview, or for embedding in other pages? I don't know, just imitating RSS-bridge.

**Comment by DIYgod** [comment]
Thank you very much for your contribution, but unfortunately, I don't think it is useful enough. If you want RSS preview, I wrote a more interesting and simple practice a long time ago, but it is also limited to toy purposes. I don't think it has much practical use in reality. https://github.com/DIYgod/RSSHub/commit/a04ad04f05b5cba8cb42338864ec138361e5dee2

**Pull request closed without merging**
