### PR TITLE
feat: add 新榜(newrank.cn)

### PR DESCRIPTION
**Pull request by lessmoe**
添加了新榜(newrank.cn)的以下信息
**微信公众号文章**：
新榜抓取的微信公众号文章信息，可以作为微信公众号文章的补充来源；
**抖音短视频**：
新榜抓取的抖音短视频信息，可以作为抖音短视频的补充来源；

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#5107: 【路由需求】新榜(newrank.cn) 作为新的微信公众号来源](https://issuehunt.io/repos/127769231/issues/5107)
---
</details>

### CODE REVIEW

**Comment by HenryQW** [comment]
Rebase 一下解决冲突吧

**Comment by flowerhood** [comment]
> 多了两个路由
你好,我通过部署vercel访问新榜微信公众号和抖音,均无法抓取rss,用系统的示例也是出现类似错误说明
https://rssh-ub-five.vercel.app/newrank/wechat/gushequ   

总出现以下错误:
Looks like something went wrong
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Hash.update (internal/crypto/hash.js:82:11)
    at md5 (/var/task/lib/utils/md5.js:4:37)
    at Object.getCookie (/var/task/lib/routes/newrank/utils.js:73:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async module.exports (/var/task/lib/routes/newrank/wechat.js:12:21)
    at async cache (/var/task/lib/middleware/cache.js:203:9)
    at async module.exports (/var/task/lib/middleware/parameter.js:8:5)
    at async module.exports (/var/task/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/var/task/lib/middleware/template.js:15:5)
    at async /var/task/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/var/task/lib/middleware/api-template.js:2:5)
    at async module.exports (/var/task/lib/middleware/utf8.js:4:5)
    at async module.exports (/var/task/lib/middleware/debug.js:14:5)
    at async grant (/var/task/lib/middleware/access-control.js:23:13)
    at async module.exports (/var/task/lib/middleware/access-control.js:31:20)
    at async module.exports (/var/task/lib/middleware/header.js:20:5)
    at async module.exports (/var/task/lib/middleware/onerror.js:20:9)
For online documentation and support please refer to docs.rsshub.app.

**Comment by lessmoe** [comment]
部署的账号密码是对的吗，我自己搭建的没有问题呀




bossdoge@126.com
 
发件人： flowerhood
发送时间： 2020-08-12 21:43
收件人： DIYgod/RSSHub
抄送： BossDoge; Author
主题： Re: [DIYgod/RSSHub] feat: add 新榜(newrank.cn) (#5254)
多了两个路由
你好,我通过部署vercel访问新榜微信公众号和抖音,均无法抓取rss,用系统的示例也是出现类似错误说明
https://rssh-ub-five.vercel.app/newrank/wechat/gushequ
总出现以下错误:
Looks like something went wrong
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
at Hash.update (internal/crypto/hash.js:82:11)
at md5 (/var/task/lib/utils/md5.js:4:37)
at Object.getCookie (/var/task/lib/routes/newrank/utils.js:73:26)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async module.exports (/var/task/lib/routes/newrank/wechat.js:12:21)
at async cache (/var/task/lib/middleware/cache.js:203:9)
at async module.exports (/var/task/lib/middleware/parameter.js:8:5)
at async module.exports (/var/task/lib/middleware/anti-hotlink.js:33:5)
at async module.exports (/var/task/lib/middleware/template.js:15:5)
at async /var/task/lib/middleware/api-response-handler.js:143:9
at async module.exports (/var/task/lib/middleware/api-template.js:2:5)
at async module.exports (/var/task/lib/middleware/utf8.js:4:5)
at async module.exports (/var/task/lib/middleware/debug.js:14:5)
at async grant (/var/task/lib/middleware/access-control.js:23:13)
at async module.exports (/var/task/lib/middleware/access-control.js:31:20)
at async module.exports (/var/task/lib/middleware/header.js:20:5)
at async module.exports (/var/task/lib/middleware/onerror.js:20:9)
For online documentation and support please refer to docs.rsshub.app.

**Comment by flowerhood** [comment]
> 部署的账号密码是对的吗，我自己搭建的没有问题呀 bossdoge@126.com 发件人： flowerhood 发送时间： 2020-08-12 21:43 收件人： DIYgod/RSSHub 抄送： BossDoge; Author 主题： Re: [DIYgod/RSSHub] feat: add 新榜(newrank.cn) (#5254) 多了两个路由 你好,我通过部署vercel访问新榜微信公众号和抖音,均无法抓取rss,用系统的示例也是出现类似错误说明 https://rssh-ub-five.vercel.app/newrank/wechat/gushequ 总出现以下错误: Looks like something went wrong TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined at Hash.update (internal/crypto/hash.js:82:11) at md5 (/var/task/lib/utils/md5.js:4:37) at Object.getCookie (/var/task/lib/routes/newrank/utils.js:73:26) at processTicksAndRejections (internal/process/task_queues.js:97:5) at async module.exports (/var/task/lib/routes/newrank/wechat.js:12:21) at async cache (/var/task/lib/middleware/cache.js:203:9) at async module.exports (/var/task/lib/middleware/parameter.js:8:5) at async module.exports (/var/task/lib/middleware/anti-hotlink.js:33:5) at async module.exports (/var/task/lib/middleware/template.js:15:5) at async /var/task/lib/middleware/api-response-handler.js:143:9 at async module.exports (/var/task/lib/middleware/api-template.js:2:5) at async module.exports (/var/task/lib/middleware/utf8.js:4:5) at async module.exports (/var/task/lib/middleware/debug.js:14:5) at async grant (/var/task/lib/middleware/access-control.js:23:13) at async module.exports (/var/task/lib/middleware/access-control.js:31:20) at async module.exports (/var/task/lib/middleware/header.js:20:5) at async module.exports (/var/task/lib/middleware/onerror.js:20:9) For online documentation and support please refer to docs.rsshub.app. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你好,我检查了新榜网站的用户名和密码,并在vercel上的环境设置上面的三个红色箭头部分均录入NEWRANK_USERNAME: 我的新榜登录用户名及NEWRANK_PASSWORD:我的新榜登陆密码,均是上述错误提示,而且我也访问了原作者@BossDoge      制作的rsshub的新榜rss地址链接也是同样的错误提示,  https://docs.rsshub.app/social-media.html#xin-bang   ,是不是原作者的rss地址已经失效了?即使我把rsshub项目fork到我的github并部署到vercel上也是毫无用处,我在rsshub上能直接访问的同样部署到我的域名上也能访问,在rsshub不能直接访问的地址同样在我的vercel域名上也无法访问,请问一下,你也是部署到vercel上面的吗?

**Comment by lessmoe** [comment]
我是自己搭的


在2020年08月13日 15:52，flowerhood 写道：

部署的账号密码是对的吗，我自己搭建的没有问题呀 bossdoge@126.com 发件人： flowerhood 发送时间： 2020-08-12 21:43 收件人： DIYgod/RSSHub 抄送： BossDoge; Author 主题： Re: [DIYgod/RSSHub] feat: add 新榜(newrank.cn) (#5254) 多了两个路由 你好,我通过部署vercel访问新榜微信公众号和抖音,均无法抓取rss,用系统的示例也是出现类似错误说明 https://rssh-ub-five.vercel.app/newrank/wechat/gushequ 总出现以下错误: Looks like something went wrong TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined at Hash.update (internal/crypto/hash.js:82:11) at md5 (/var/task/lib/utils/md5.js:4:37) at Object.getCookie (/var/task/lib/routes/newrank/utils.js:73:26) at processTicksAndRejections (internal/process/task_queues.js:97:5) at async module.exports (/var/task/lib/routes/newrank/wechat.js:12:21) at async cache (/var/task/lib/middleware/cache.js:203:9) at async module.exports (/var/task/lib/middleware/parameter.js:8:5) at async module.exports (/var/task/lib/middleware/anti-hotlink.js:33:5) at async module.exports (/var/task/lib/middleware/template.js:15:5) at async /var/task/lib/middleware/api-response-handler.js:143:9 at async module.exports (/var/task/lib/middleware/api-template.js:2:5) at async module.exports (/var/task/lib/middleware/utf8.js:4:5) at async module.exports (/var/task/lib/middleware/debug.js:14:5) at async grant (/var/task/lib/middleware/access-control.js:23:13) at async module.exports (/var/task/lib/middleware/access-control.js:31:20) at async module.exports (/var/task/lib/middleware/header.js:20:5) at async module.exports (/var/task/lib/middleware/onerror.js:20:9) For online documentation and support please refer to docs.rsshub.app. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你好,我检查了新榜网站的用户名和密码,并在vercel上的环境设置上面的三个红色箭头部分均录入NEWRANK_USERNAME: 我的新榜登录用户名及NEWRANK_PASSWORD:我的新榜登陆密码,均是上述错误提示,而且我也访问了原作者@BossDoge 制作的rsshub的新榜rss地址链接也是同样的错误提示, https://docs.rsshub.app/social-media.html#xin-bang ,是不是原作者的rss地址已经失效了?即使我把rsshub项目fork到我的github并部署到vercel上也是毫无用处,我在rsshub上能直接访问的同样部署到我的域名上也能访问,在rsshub不能直接访问的地址同样在我的vercel域名上也无法访问,请问一下,你也是部署到vercel上面的吗?

**Comment by lessmoe** [comment]
redis缓存开了吗


在2020年08月13日 15:52，flowerhood 写道：

部署的账号密码是对的吗，我自己搭建的没有问题呀 bossdoge@126.com 发件人： flowerhood 发送时间： 2020-08-12 21:43 收件人： DIYgod/RSSHub 抄送： BossDoge; Author 主题： Re: [DIYgod/RSSHub] feat: add 新榜(newrank.cn) (#5254) 多了两个路由 你好,我通过部署vercel访问新榜微信公众号和抖音,均无法抓取rss,用系统的示例也是出现类似错误说明 https://rssh-ub-five.vercel.app/newrank/wechat/gushequ 总出现以下错误: Looks like something went wrong TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined at Hash.update (internal/crypto/hash.js:82:11) at md5 (/var/task/lib/utils/md5.js:4:37) at Object.getCookie (/var/task/lib/routes/newrank/utils.js:73:26) at processTicksAndRejections (internal/process/task_queues.js:97:5) at async module.exports (/var/task/lib/routes/newrank/wechat.js:12:21) at async cache (/var/task/lib/middleware/cache.js:203:9) at async module.exports (/var/task/lib/middleware/parameter.js:8:5) at async module.exports (/var/task/lib/middleware/anti-hotlink.js:33:5) at async module.exports (/var/task/lib/middleware/template.js:15:5) at async /var/task/lib/middleware/api-response-handler.js:143:9 at async module.exports (/var/task/lib/middleware/api-template.js:2:5) at async module.exports (/var/task/lib/middleware/utf8.js:4:5) at async module.exports (/var/task/lib/middleware/debug.js:14:5) at async grant (/var/task/lib/middleware/access-control.js:23:13) at async module.exports (/var/task/lib/middleware/access-control.js:31:20) at async module.exports (/var/task/lib/middleware/header.js:20:5) at async module.exports (/var/task/lib/middleware/onerror.js:20:9) For online documentation and support please refer to docs.rsshub.app. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你好,我检查了新榜网站的用户名和密码,并在vercel上的环境设置上面的三个红色箭头部分均录入NEWRANK_USERNAME: 我的新榜登录用户名及NEWRANK_PASSWORD:我的新榜登陆密码,均是上述错误提示,而且我也访问了原作者@BossDoge 制作的rsshub的新榜rss地址链接也是同样的错误提示, https://docs.rsshub.app/social-media.html#xin-bang ,是不是原作者的rss地址已经失效了?即使我把rsshub项目fork到我的github并部署到vercel上也是毫无用处,我在rsshub上能直接访问的同样部署到我的域名上也能访问,在rsshub不能直接访问的地址同样在我的vercel域名上也无法访问,请问一下,你也是部署到vercel上面的吗?

**Comment by flowerhood** [comment]
> 我是自己搭的 在2020年08月13日 15:52，flowerhood 写道： 部署的账号密码是对的吗，我自己搭建的没有问题呀 bossdoge@126.com 发件人： flowerhood 发送时间： 2020-08-12 21:43 收件人： DIYgod/RSSHub 抄送： BossDoge; Author 主题： Re: [DIYgod/RSSHub] feat: add 新榜(newrank.cn) (#5254) 多了两个路由 你好,我通过部署vercel访问新榜微信公众号和抖音,均无法抓取rss,用系统的示例也是出现类似错误说明 https://rssh-ub-five.vercel.app/newrank/wechat/gushequ 总出现以下错误: Looks like something went wrong TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined at Hash.update (internal/crypto/hash.js:82:11) at md5 (/var/task/lib/utils/md5.js:4:37) at Object.getCookie (/var/task/lib/routes/newrank/utils.js:73:26) at processTicksAndRejections (internal/process/task_queues.js:97:5) at async module.exports (/var/task/lib/routes/newrank/wechat.js:12:21) at async cache (/var/task/lib/middleware/cache.js:203:9) at async module.exports (/var/task/lib/middleware/parameter.js:8:5) at async module.exports (/var/task/lib/middleware/anti-hotlink.js:33:5) at async module.exports (/var/task/lib/middleware/template.js:15:5) at async /var/task/lib/middleware/api-response-handler.js:143:9 at async module.exports (/var/task/lib/middleware/api-template.js:2:5) at async module.exports (/var/task/lib/middleware/utf8.js:4:5) at async module.exports (/var/task/lib/middleware/debug.js:14:5) at async grant (/var/task/lib/middleware/access-control.js:23:13) at async module.exports (/var/task/lib/middleware/access-control.js:31:20) at async module.exports (/var/task/lib/middleware/header.js:20:5) at async module.exports (/var/task/lib/middleware/onerror.js:20:9) For online documentation and support please refer to docs.rsshub.app. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 你好,我检查了新榜网站的用户名和密码,并在vercel上的环境设置上面的三个红色箭头部分均录入NEWRANK_USERNAME: 我的新榜登录用户名及NEWRANK_PASSWORD:我的新榜登陆密码,均是上述错误提示,而且我也访问了原作者@BossDoge 制作的rsshub的新榜rss地址链接也是同样的错误提示, https://docs.rsshub.app/social-media.html#xin-bang ,是不是原作者的rss地址已经失效了?即使我把rsshub项目fork到我的github并部署到vercel上也是毫无用处,我在rsshub上能直接访问的同样部署到我的域名上也能访问,在rsshub不能直接访问的地址同样在我的vercel域名上也无法访问,请问一下,你也是部署到vercel上面的吗? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我是手工部署并用npm start启动的,不是用Docker Compose 部署的.没有部署puppeteer 和 redis 依赖,一定要设置redis缓存吗?

**Comment by lessmoe** [comment]
当初我就是照猫画虎做的新榜，你可以加一个cookie登陆的选项。我不是程序员，有啥问题我也没辙😭


在2020年08月13日 16:13，flowerhood 写道：

我是自己搭的 在2020年08月13日 15:52，flowerhood 写道： 部署的账号密码是对的吗，我自己搭建的没有问题呀 bossdoge@126.com 发件人： flowerhood 发送时间： 2020-08-12 21:43 收件人： DIYgod/RSSHub 抄送： BossDoge; Author 主题： Re: [DIYgod/RSSHub] feat: add 新榜(newrank.cn) (#5254) 多了两个路由 你好,我通过部署vercel访问新榜微信公众号和抖音,均无法抓取rss,用系统的示例也是出现类似错误说明 https://rssh-ub-five.vercel.app/newrank/wechat/gushequ 总出现以下错误: Looks like something went wrong TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined at Hash.update (internal/crypto/hash.js:82:11) at md5 (/var/task/lib/utils/md5.js:4:37) at Object.getCookie (/var/task/lib/routes/newrank/utils.js:73:26) at processTicksAndRejections (internal/process/task_queues.js:97:5) at async module.exports (/var/task/lib/routes/newrank/wechat.js:12:21) at async cache (/var/task/lib/middleware/cache.js:203:9) at async module.exports (/var/task/lib/middleware/parameter.js:8:5) at async module.exports (/var/task/lib/middleware/anti-hotlink.js:33:5) at async module.exports (/var/task/lib/middleware/template.js:15:5) at async /var/task/lib/middleware/api-response-handler.js:143:9 at async module.exports (/var/task/lib/middleware/api-template.js:2:5) at async module.exports (/var/task/lib/middleware/utf8.js:4:5) at async module.exports (/var/task/lib/middleware/debug.js:14:5) at async grant (/var/task/lib/middleware/access-control.js:23:13) at async module.exports (/var/task/lib/middleware/access-control.js:31:20) at async module.exports (/var/task/lib/middleware/header.js:20:5) at async module.exports (/var/task/lib/middleware/onerror.js:20:9) For online documentation and support please refer to docs.rsshub.app. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 你好,我检查了新榜网站的用户名和密码,并在vercel上的环境设置上面的三个红色箭头部分均录入NEWRANK_USERNAME: 我的新榜登录用户名及NEWRANK_PASSWORD:我的新榜登陆密码,均是上述错误提示,而且我也访问了原作者@BossDoge 制作的rsshub的新榜rss地址链接也是同样的错误提示, https://docs.rsshub.app/social-media.html#xin-bang ,是不是原作者的rss地址已经失效了?即使我把rsshub项目fork到我的github并部署到vercel上也是毫无用处,我在rsshub上能直接访问的同样部署到我的域名上也能访问,在rsshub不能直接访问的地址同样在我的vercel域名上也无法访问,请问一下,你也是部署到vercel上面的吗? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我是手工部署并用npm start启动的,不是用Docker Compose 部署的.没有部署puppeteer 和 redis 依赖,一定要设置redis缓存吗?

**Comment by lessmoe** [comment]
大佬有兴趣的话可以优化一下😁


在2020年08月13日 16:13，flowerhood 写道：

我是自己搭的 在2020年08月13日 15:52，flowerhood 写道： 部署的账号密码是对的吗，我自己搭建的没有问题呀 bossdoge@126.com 发件人： flowerhood 发送时间： 2020-08-12 21:43 收件人： DIYgod/RSSHub 抄送： BossDoge; Author 主题： Re: [DIYgod/RSSHub] feat: add 新榜(newrank.cn) (#5254) 多了两个路由 你好,我通过部署vercel访问新榜微信公众号和抖音,均无法抓取rss,用系统的示例也是出现类似错误说明 https://rssh-ub-five.vercel.app/newrank/wechat/gushequ 总出现以下错误: Looks like something went wrong TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined at Hash.update (internal/crypto/hash.js:82:11) at md5 (/var/task/lib/utils/md5.js:4:37) at Object.getCookie (/var/task/lib/routes/newrank/utils.js:73:26) at processTicksAndRejections (internal/process/task_queues.js:97:5) at async module.exports (/var/task/lib/routes/newrank/wechat.js:12:21) at async cache (/var/task/lib/middleware/cache.js:203:9) at async module.exports (/var/task/lib/middleware/parameter.js:8:5) at async module.exports (/var/task/lib/middleware/anti-hotlink.js:33:5) at async module.exports (/var/task/lib/middleware/template.js:15:5) at async /var/task/lib/middleware/api-response-handler.js:143:9 at async module.exports (/var/task/lib/middleware/api-template.js:2:5) at async module.exports (/var/task/lib/middleware/utf8.js:4:5) at async module.exports (/var/task/lib/middleware/debug.js:14:5) at async grant (/var/task/lib/middleware/access-control.js:23:13) at async module.exports (/var/task/lib/middleware/access-control.js:31:20) at async module.exports (/var/task/lib/middleware/header.js:20:5) at async module.exports (/var/task/lib/middleware/onerror.js:20:9) For online documentation and support please refer to docs.rsshub.app. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 你好,我检查了新榜网站的用户名和密码,并在vercel上的环境设置上面的三个红色箭头部分均录入NEWRANK_USERNAME: 我的新榜登录用户名及NEWRANK_PASSWORD:我的新榜登陆密码,均是上述错误提示,而且我也访问了原作者@BossDoge 制作的rsshub的新榜rss地址链接也是同样的错误提示, https://docs.rsshub.app/social-media.html#xin-bang ,是不是原作者的rss地址已经失效了?即使我把rsshub项目fork到我的github并部署到vercel上也是毫无用处,我在rsshub上能直接访问的同样部署到我的域名上也能访问,在rsshub不能直接访问的地址同样在我的vercel域名上也无法访问,请问一下,你也是部署到vercel上面的吗? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我是手工部署并用npm start启动的,不是用Docker Compose 部署的.没有部署puppeteer 和 redis 依赖,一定要设置redis缓存吗?

**Comment by flowerhood** [comment]
> > 部署的账号密码是对的吗，我自己搭建的没有问题呀 [bossdoge@126.com](mailto:bossdoge@126.com) 发件人： flowerhood 发送时间： 2020-08-12 21:43 收件人： DIYgod/RSSHub 抄送： BossDoge; Author 主题： Re: [DIYgod/RSSHub] feat: add 新榜(newrank.cn) (#5254) 多了两个路由 你好,我通过部署vercel访问新榜微信公众号和抖音,均无法抓取rss,用系统的示例也是出现类似错误说明 https://rssh-ub-five.vercel.app/newrank/wechat/gushequ 总出现以下错误: Looks like something went wrong TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined at Hash.update (internal/crypto/hash.js:82:11) at md5 (/var/task/lib/utils/md5.js:4:37) at Object.getCookie (/var/task/lib/routes/newrank/utils.js:73:26) at processTicksAndRejections (internal/process/task_queues.js:97:5) at async module.exports (/var/task/lib/routes/newrank/wechat.js:12:21) at async cache (/var/task/lib/middleware/cache.js:203:9) at async module.exports (/var/task/lib/middleware/parameter.js:8:5) at async module.exports (/var/task/lib/middleware/anti-hotlink.js:33:5) at async module.exports (/var/task/lib/middleware/template.js:15:5) at async /var/task/lib/middleware/api-response-handler.js:143:9 at async module.exports (/var/task/lib/middleware/api-template.js:2:5) at async module.exports (/var/task/lib/middleware/utf8.js:4:5) at async module.exports (/var/task/lib/middleware/debug.js:14:5) at async grant (/var/task/lib/middleware/access-control.js:23:13) at async module.exports (/var/task/lib/middleware/access-control.js:31:20) at async module.exports (/var/task/lib/middleware/header.js:20:5) at async module.exports (/var/task/lib/middleware/onerror.js:20:9) For online documentation and support please refer to docs.rsshub.app. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> [图片示例](https://i.niupic.com/images/2020/08/13/8w9S.png)
> 你好,我检查了新榜网站的用户名和密码,并在vercel上的环境设置上面的三个红色箭头部分均录入NEWRANK_USERNAME: 我的新榜登录用户名及NEWRANK_PASSWORD:我的新榜登陆密码,均是上述错误提示,而且我也访问了原作者@BossDoge 制作的rsshub的新榜rss地址链接也是同样的错误提示, https://docs.rsshub.app/social-media.html#xin-bang ,是不是原作者的rss地址已经失效了?即使我把rsshub项目fork到我的github并部署到vercel上也是毫无用处,我在rsshub上能直接访问的同样部署到我的域名上也能访问,在rsshub不能直接访问的地址同样在我的vercel域名上也无法访问,请问一下,你也是部署到vercel上面的吗?

谢谢提醒,折腾了两天,刚才彻底删除并重新部署了rsshub及相关模块,还是没有解决,接近放弃的时候,分析错误提示: Looks like something went wrong TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. 提示变量值应该是字符串,而我在环境配置文件中配置用户名和密码都没有加上引号,所以返回变量类型错误,加上引号号返回类型自然变为string类型,果然加上,就可以正常部署打开了,一个引号的疏忽浪费了2天时间,实在是惭愧

**Pull request merged**
