### PR TITLE
feat: 📖 📚 Add new routers

### PR DESCRIPTION
**Pull request by yech1990**
- 📖 Add router for linkresearch (/linkresearcher/:params)

  - support multiple categories: `theses`, `information`, `careers`
  - both **subject** and **columns** filter are supported
  - *query* by keywords is also supported
  - update documentation

---

- 📚 Add router for cell journal (/cell/cell/current)

  - with graphical highlight
  - both `current` and `inpress` are supported

### CODE REVIEW

**Comment by yech1990** [comment]
fix https://github.com/DIYgod/RSSHub/issues/4080

**Comment by yech1990** [comment]
support multiple categories: theses, information, careers

image

**Comment by hoilc** [comment]
> support multiple categories: theses, information, careers
> 
> image

这是啥阅读器🤔️

**Comment by yech1990** [comment]
feedreader

**Comment by yefoenix** [comment]
太棒了，非常感谢！
能否把关键词搜索的结果页面也做上呢？例如
https://www.linkresearcher.com/searchall?from=0&query=%E6%96%B0%E5%86%A0&size=10&tab=theses&type=LATEST

再次感谢！

**Comment by yech1990** [comment]
add router for cell press

image

**Comment by yech1990** [comment]
@yefoenix 
try https://rsshub.app/linkresearcher/category=theses&subject=生物&query=新冠

**Pull request merged**
