### PR TITLE
fix: route syntax for hono

### LINKED ISSUE #14623: github files commits 路由工作异常
### 路由地址

```routes
/github/file/:user/:repo/:branch/:filepath+
```

### 完整路由地址

```fullroutes
/github/file/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Full_MultiMode.ini
/github/file/DIYgod/RSSHub/master/docker-compose.yml
```

### 相关文档

https://docs.rsshub.app/zh/routes/programming#github-files-commits

### 预期是什么？

正常拉取指定文件的相关commits

### 实际发生了什么？

拉取了几乎所有的commits，或报错文件无法找到

### 部署

自建

### 部署相关信息

OS:Arch Linux, Docker: v25.0.3

### 额外信息

```shell
Route requested: /github/file/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Full_MultiMode.ini

Error message: wrong path

Helpful Information to provide when opening issue:
Path: /github/file/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Full_MultiMode.ini
Node version: v21.6.2
Git Hash: 8171d92
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by ouuan**
## Involved Issue / 该 PR 相关 Issue

Close #14623

## Example for the Proposed Route(s) / 路由地址示例

```routes
/github/file/DIYgod/RSSHub/master/lib/router.js
/whu/news
/whu/news/
/whu/news/wdzx/zhxw
/gov/moa/xw/zwdt
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Documentation / 文档说明
- [ ] Full text / 全文获取
  - [ ] Use cache / 使用缓存
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

## Note / 说明

It seems that Hono does not support optional param with regular expression: https://github.com/orgs/honojs/discussions/1536

### CODE REVIEW

**Comment by TonyRL** [comment]
Regarding /foo and /foo/ matching different routes, this behaviour can be changed in [strict mode](https://hono.dev/api/hono#strict-mode)

**Comment by ouuan** [comment]
> Regarding /foo and /foo/ matching different routes, this behaviour can be changed in [strict mode](https://hono.dev/api/hono#strict-mode)

I'm on my bed now. But in case that I forget: we may need to test whether strict mode changes the trailing slash of `param` in `:param{.+}`.

**Comment by ouuan** [comment]
> I'm on my bed now. But in case that I forget: we may need to test whether strict mode changes the trailing slash of `param` in `:param{.+}`.

When `strict: false`, the trailing slash in `:param{.+}` is also stripped. This might be problematic in some routes.

**Comment by DIYgod** [comment]
I am very worried that this will further increase the difficulty of subsequent maintenance. I think it can be replaced by the Regexp syntax supported by Hono.

**Comment by ouuan** [comment]
> I am very worried that this will further increase the difficulty of subsequent maintenance. I think it can be replaced by the Regexp syntax supported by Hono.

I'm not aware of how the `:param*` syntax can be exactly expressed by a single route in Hono.

**Comment by ouuan** [comment]
An alternative solution is to contribute this syntax to Hono.

**Comment by ouuan** [comment]
I think we can merge it first to fix these broken routes. Maybe switch to better solutions later.

**Comment by DIYgod** [comment]
Thanks so much!

**Pull request merged**
