### PR TITLE
fix: jandan image can't load

### LINKED ISSUE #11528: 煎蛋网 所有图片都无法显示
### 路由地址

```routes
/jandan/:category?
```

### 完整路由地址

```fullroutes
/jandan/top
```

### 相关文档

https://docs.rsshub.app/picture.html#jian-dan

### 预期是什么？

正常显示图片内容

### 实际发生了什么？

近期因为jiandan图床更换，目前所有图片都不可显示。

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by bxb100**
## Example for the Proposed Route(s) / 路由地址示例

```routes
/jandan
/jandan/top-4h
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

## Note / 说明

same logic used in https://github.com/bxb100/jandan-plus/blob/53a0ccd6c81903407a36eb65efabc6d9d7c3e237/rules.json

### CODE REVIEW

**Review by TonyRL — COMMENTED** [review]
Are you sure it can be shown properly in RSS reader? AFAIK sinaimg also does referer check.

**Comment by bxb100** [comment]
If you are using a web reader, you should add an extension to bypass the referral check. If you are using a local reader, Sina will not restrict localhost readability.

anyway, the Sina image link is better than `moyu.im`

**Comment by TonyRL** [comment]
If it still requires a browser extension to bypass the referral check, that means #11528 is still not fixed. Besides that, I'm afraid the issue still exists, as you can preview the RSS output using [debug.html](https://docs.rsshub.app/guide/parameters#debug-html) like `/jandan/top-4h?format=0.debug.html` without the aid of browser extension.

**Comment by bxb100** [comment]
remove `Close #11528`

**Pull request merged**
