### PR TITLE
docs: fix Route's path and example of chinacef

### PR DESCRIPTION
**Pull request by kdanfly**
## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
NOROUTE
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [ ] 新的路由 New Route
  - [ ] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [x] 文档说明 Documentation
  - [x] 中文文档 CN
  - [ ] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

### CODE REVIEW

**Comment by TonyRL** [comment]
FYI, both `/chinacef/:experts_id/` and `/chinacef/:experts_id` works when I was testing

**Comment by kdanfly** [comment]
Yeah, It's odd, I noticed that when this PR merged. But It's not working without `/` ending when I had tested earlyer.

**Comment by kdanfly** [comment]
Same route issus in `https://rsshub.app/chinacef`, it's works with `/` ending.

**Comment by TonyRL** [comment]
Errors are also cached on demo instance. You can try with some unseen experts_id, e.g., `/chinacef/35`

**Comment by kdanfly** [comment]
About `https://rsshub.app/chinacef`, I think it's beacuse of v2 router config `router.get('/', require('./index'));` 

Does it mean the doc must be `https://rsshub.app/chinacef/` ?

**Comment by TonyRL** [comment]
Both `example.com/chinacef` and `example.com/chinacef/` should work for `router.get('/', ())`;

**Comment by kdanfly** [comment]
> Both `example.com/chinacef` and `example.com/chinacef/` should work for `router.get('/', ())`;

I had tested on localhost by fresh code, `http://localhost:1200/chinacef` was worked, but it's not working on `https://rsshub.app/chinacef`

**Comment by TonyRL** [comment]
>Errors are also cached on demo instance. You can try with some unseen experts_id, e.g., `/chinacef/35`

_Originally posted by @TonyRL in https://github.com/DIYgod/RSSHub/issues/9552#issuecomment-1100887832_

**Pull request merged**
